const cityList = [
  "MARIEHAMN",
  "Durrës",
  "TIRANA",
  "Annaba",
  "Batna",
  "Béchar",
  "Bejaïa",
  "Beskra",
  "Bordj Bou Arreridj",
  "Bordj el Kiffan",
  "Ech Cheliff (El Asnam)",
  "El Boulaïda (Blida)",
  "ALGIERS (EL DJAZAIR)",
  "El Djelfa",
  "El Eulma",
  "El Wad",
  "Ghardaïa",
  "Ghilizane",
  "Guelma",
  "Jijel",
  "Lemdiyya (Medea)",
  "Mestghanem (Mostaganem)",
  "M'Sila",
  "Qacentina (Constantine)",
  "Saïda",
  "Sidi-bel-Abbès",
  "Skikda",
  "Souq Ahras",
  "Stif (Sétif)",
  "Tbessa",
  "Tihert",
  "Tilimsen (Tlemcen)",
  "Touggourt",
  "Wahran (Oran)",
  "Wargla",
  "PAGO PAGO",
  "ANDORRA LA VELLA",
  "THE VALLEY",
  "ST. JOHN",
  "Bahía Blanca-Cerri",
  "BUENOS AIRES",
  "Catamarca",
  "Comodoro Rivadavia-Rada Tilly",
  "Concordia",
  "Córdoba",
  "Corrientes",
  "Formosa",
  "La Plata",
  "La Rioja",
  "San Luis - El Chorrillo",
  "Mar del Plata-Batán",
  "Mendoza",
  "Neuquén-Plottier",
  "Paraná",
  "Posadas",
  "Resistencia",
  "Río Cuarto",
  "Rosario",
  "Salta",
  "San Juan",
  "San Salvador de Jujuy-Palpalá",
  "Santa Fé",
  "Santa Rosa-Toay",
  "Santiago del Estero-La Banda",
  "Tucumán-Tafí Viejo",
  "Ushuaia-Río Grande",
  "Rawson-Trelew-Playa Unión",
  "San Nicolás-Villa Constitución",
  "Avellaneda",
  "General San Martín",
  "La Matanza",
  "Lanus",
  "Lomas de Zamora",
  "Morón",
  "Quilmes",
  "San Fernando",
  "San Isidro",
  "San Miguel de Tucumán",
  "Vicente López",
  "Gyumri (Leninakan)",
  "YEREVAN",
  "Vanadzoz (Kirovakan)",
  "ORANJESTAD",
  "Adelaide",
  "Brisbane",
  "Cairns",
  "Canberra-Queanbeyan",
  "Central Coast",
  "Darwin",
  "Geelong",
  "Gold Coast-Tweed Heads",
  "Greater Adelaide",
  "Greater Brisbane",
  "Greater Darwin",
  "Greater Hobart",
  "Greater Melbourne",
  "Greater Perth",
  "Greater Sydney",
  "Hobart",
  "Melbourne",
  "Newcastle-Maitland",
  "Perth",
  "Sunshine Coast",
  "Sydney",
  "Toowoomba",
  "Townsville",
  "Wollongong",
  "CANBERRA",
  "Greater Wollongong",
  "Newcastle",
  "Albury-Wodonga",
  "Launceston",
  "Gold Coast",
  "Bregenz",
  "Eisenstadt",
  "Graz",
  "Innsbruck",
  "Klagenfurt",
  "Linz",
  "Salzburg",
  "Sankt Pölten",
  "WIEN",
  "BAKU",
  "Ganja",
  "Sumgayit",
  "NASSAU",
  "MANAMA",
  "Barisal",
  "Bogra",
  "Brahmanbaria",
  "Chittagong",
  "Comilla",
  "DHAKA",
  "Dinajpur",
  "Gazipur",
  "Jamalpur",
  "Jessore",
  "Kadamrasul",
  "Khulna",
  "Mymensingh",
  "Naogaon",
  "Narayanganj",
  "Narsingdi",
  "Nawabganj",
  "Pabna",
  "Rajshahi",
  "Rangpur",
  "Saidpur",
  "Sirajganj",
  "Tangail",
  "Tongi",
  "BRIDGETOWN",
  "Baranovichi",
  "Bobruisk",
  "Borisov",
  "Brest",
  "Gomel",
  "Grodno",
  "MINSK",
  "Mogilev",
  "Mozir",
  "Novopolotsk",
  "Orsha",
  "Pinsk",
  "Soligorsk",
  "Vitebsk",
  "Lida",
  "Anderlecht",
  "Antwerpen (Anvers)",
  "Brugge",
  "BRUXELLES (BRUSSEL)",
  "Charleroi",
  "Gent (Gand)",
  "Liège (Luik)",
  "Namur",
  "Schaerbeek",
  "HAMILTON",
  "Town of St. George",
  "THIMPHU",
  "Cochabamba",
  "El Alto",
  "LA PAZ",
  "Oruro",
  "Potosí",
  "Santa Cruz",
  "SUCRE",
  "Tarija",
  "Banja Luka",
  "Doboj",
  "Mostar",
  "Prijedor",
  "SARAJEVO",
  "Tuzla",
  "Zenica",
  "Francistown",
  "GABORONE",
  "Abaeteluba",
  "Açailândia",
  "Aguas Lindas de Goiás",
  "Alagoinhas",
  "Almirante Tamandaré",
  "Alvorada",
  "Americana",
  "Ananindeua",
  "Anápolis",
  "Angra dos Reis",
  "Aparecida de Goiania",
  "Apucarana",
  "Aracaju",
  "Araçatuba",
  "Araguaina",
  "Araguario",
  "Arapiraca",
  "Arapongas",
  "Araraquara",
  "Araras",
  "Araruama",
  "Araucária",
  "Atibaia",
  "Bacabal",
  "Bagé",
  "Balneário Camboriú",
  "Barbacena",
  "Barra Mansa",
  "Barreiras",
  "Barretos",
  "Barueri",
  "Bauru",
  "Belém",
  "Belford Roxo",
  "Belo Horizonte",
  "Bento Gonçalves",
  "Betim",
  "Birigui",
  "Blumenou",
  "Boa Vista",
  "Botucatu",
  "Bragança",
  "Bragança Paulista",
  "BRASILIA",
  "Brusque",
  "Cabo de Santo Agostinho",
  "Cabo Frio",
  "Cachoeirinha",
  "Cachoeiro de Itapemirim",
  "Camacari",
  "Camaragibe",
  "Cametá",
  "Campina Grande",
  "Campinas",
  "Campo Grande",
  "Campo Largo",
  "Campos dos Goytacazes",
  "Canoas",
  "Carapicuíba",
  "Caraguatatuba",
  "Cariacica",
  "Caruaru",
  "Cascavel",
  "Castanhal",
  "Catanduva",
  "Caucaia",
  "Caxias",
  "Caxias do Sul",
  "Chapecó",
  "Codo",
  "Colatina",
  "Colombo",
  "Conselheiro Lafaiete",
  "Contagem",
  "Coronel Fabriciano",
  "Corumbá",
  "Cotia",
  "Crato",
  "Criciúma",
  "Cubatao",
  "Cuiabá",
  "Curitiba",
  "Diadema",
  "Divinópolis",
  "Dourados",
  "Duque de Caxias",
  "Embu",
  "Eunápolis",
  "Feira de Santana",
  "Ferraz de Vasconcelos",
  "Florianópolis",
  "Fortaleza",
  "Foz do Iguaçu",
  "Franca",
  "Francisco Morato",
  "Franco da Rocha",
  "Garanhuns",
  "Goiânia",
  "Governador Valadares",
  "Gravatai",
  "Guarapari",
  "Guarapuava",
  "Guaratinguetá",
  "Guarujá",
  "Guarulhos",
  "Hortolandia",
  "Ibirité",
  "Igarassu",
  "Ilhéus",
  "Imperatriz",
  "Indaiatuba",
  "Ipatinga",
  "Itabiraí",
  "Itaboraí",
  "Itabuna",
  "Itaguaí",
  "Itajaí",
  "Itapecerica da Serra",
  "Itapetininga",
  "Itapevi",
  "Itapipoca",
  "Itaquaquecetuba",
  "Itatiba",
  "Itu",
  "Jaboatao dos Guarapes",
  "Jacareí",
  "Jandira",
  "Jaraguá do Sul",
  "Jaú",
  "Jequié",
  "Ji-Paraná",
  "Joao Pessoa",
  "Joinville",
  "Juazeiro",
  "Juàzeiro do Norte",
  "Juiz de Fora",
  "Jundiaí",
  "Lages",
  "Lauro de Freitas",
  "Limeira",
  "Linhares",
  "Londrina",
  "Luziânia",
  "Macae",
  "Macapá",
  "Maceió",
  "Magé",
  "Manaus",
  "Maraba",
  "Maracanau",
  "Maranguape",
  "Maricá",
  "Marília",
  "Maringá",
  "Marituba",
  "Mauá",
  "Mesquita",
  "Moji das Cruzes",
  "Moji-Guaçu",
  "Montes Claros",
  "Mossoró",
  "Muriaé",
  "Natal",
  "Nilópolis",
  "Niterói",
  "Nossa Senhora do Socorro",
  "Nova Friburgo",
  "Nova Iguaçu",
  "Nôvo Hamburgo",
  "Olinda",
  "Osasco",
  "Ourinhos",
  "Paço do Lumiar",
  "Palhoça",
  "Palmas",
  "Paranaguá",
  "Parauapebas",
  "Parintins",
  "Parnaíba",
  "Parnamirim",
  "Passo Fundo",
  "Passos",
  "Patos",
  "Patos de Minas",
  "Paulista",
  "Paulo Afonso",
  "Pelotas",
  "Petrolina",
  "Petrópolis",
  "Pindamonhangaba",
  "Pinhais",
  "Piracicaba",
  "Poà",
  "Poços de Caldas",
  "Ponta Grossa",
  "Porto Alegre",
  "Porto Seguro",
  "Porto Velho",
  "Pouso Alegre",
  "Praia Grande",
  "Presidente Prudente",
  "Queimados",
  "Recife",
  "Resende",
  "Ribeirao das Neves",
  "Ribeirao Pires",
  "Ribeirao Prêto",
  "Rio Branco",
  "Rio Claro",
  "Rio das Ostras",
  "Rio de Janeiro",
  "Rio Grande",
  "Rio Verde",
  "Rondonópolis",
  "Sabára",
  "Salto",
  "Salvador",
  "Santa Bárbara D'Oeste",
  "Santa Cruz do Sul",
  "Santa Luzia (Minas Gerais)",
  "Santa Maria",
  "Santa Rita",
  "Santana",
  "Santana de Parnaíba",
  "Santarém",
  "Santo André",
  "Santos",
  "Sao Bernardo do Campo",
  "Sao Caetano do Sul",
  "Sao Carlo",
  "Sao Gonçalo",
  "Sao Joao de Meriti",
  "Sao José",
  "Sao José de Ribamar",
  "Sao José do Rio Prêto",
  "Sao José dos Campos",
  "Sao José dos Pinhais",
  "Sao Leopoldo",
  "São Lourenço da Mata",
  "Sao Luís",
  "São Mateus",
  "Sao Paulo",
  "Sao Vicente",
  "Sapucaia do Sul",
  "Serra",
  "Sertaozinho",
  "Sete Lagoas",
  "Simoes Filho",
  "Sinop",
  "Sobral",
  "Sorocaba",
  "Sumaré",
  "Susano",
  "Taboao da Serra",
  "Tatuí",
  "Taubaté",
  "Teixeira de Freitas",
  "Teófilo Otoni",
  "Teresina",
  "Teresópolis",
  "Timon",
  "Toledo",
  "Três Lagoas",
  "Trindade",
  "Ubá",
  "Uberaba",
  "Uberlândia",
  "Umuarama",
  "Uruguaiana",
  "Valinhos",
  "Valparaíso de Goiás",
  "Varginha",
  "Varzea Grande",
  "Varzea Paulista",
  "Vespasiano",
  "Viamao",
  "Vila Velha",
  "Vitória",
  "Vitória da Conquista",
  "Vitória de Santo Antao",
  "Volta Redonda",
  "Votorantim",
  "ROAD TOWN",
  "BANDAR SERI BEGAWAN",
  "Burgas",
  "Pleven",
  "Plovdiv",
  "Ruse",
  "SOFIA",
  "Stara Zagora",
  "Varna",
  "Banfora",
  "Bobo Dioulasso",
  "Dédougou",
  "Dori",
  "Fada N'gourma",
  "Gorom-Gorom",
  "Kaya",
  "Koudougou",
  "OUAGADOUGOU",
  "Ouahigouya",
  "Pouytenga",
  "Solenzo",
  "Tenkodogo",
  "BUJUMBURA",
  "PRAIA",
  "Bafoussam",
  "Bamenda",
  "Bertoua",
  "Douala",
  "Edéa",
  "Garoua",
  "Kousséri",
  "Kumba",
  "Maroua",
  "Ngaoundéré",
  "Nkongsamba",
  "YAOUNDE",
  "Brampton",
  "Burlington",
  "Burnaby",
  "Calgary",
  "Edmonton",
  "Gatineau",
  "Greater Sudbury / Grand Sudbury",
  "Halifax",
  "Hamilton",
  "Kitchener-Cambridge-Waterloo",
  "Laval",
  "London",
  "Longueuil",
  "Markham",
  "Mississauga",
  "Montréal",
  "Oakville",
  "OTTAWA",
  "Ottawa - Gatineau",
  "Québec",
  "Regina",
  "Richmond",
  "Richmond Hill",
  "Saskatoon",
  "Sherbrooke",
  "Surrey",
  "Toronto",
  "Vancouver",
  "Vaughan",
  "Windsor",
  "Winnipeg",
  "Abbotsford-Mission",
  "Barrie",
  "Brantford",
  "Guelph",
  "Kelowna",
  "Kingston",
  "Moncton",
  "Oshawa",
  "Peterborough",
  "Saguenay",
  "Saint John",
  "St Catharines-Niagara",
  "St. John's",
  "Thunder Bay",
  "Trois-Rivières",
  "Victoria",
  "Cambridge",
  "Cape Breton",
  "Chatham-Kent",
  "Coquitlam",
  "Lévis V",
  "Saanich",
  "Whitby",
  "GEORGE TOWN",
  "BANGUI",
  "N'DJAMENA",
  "Alto Hospicio",
  "Antofagasta",
  "Arica",
  "Calama",
  "Chiguallante",
  "Chillán",
  "Concepción",
  "Coronel",
  "Copiapó",
  "Coquimbo",
  "Curicó",
  "Iquique",
  "La Serena",
  "Los Angeles",
  "Osorno",
  "Puente Alto",
  "Puerto Montt",
  "Punta Arenas",
  "Quilpué",
  "Rancagua",
  "San Bernardo",
  "San Pedro de la Paz",
  "SANTIAGO",
  "Talca",
  "Talcahuano",
  "Temuco",
  "Valdivia",
  "Valparaíso",
  "Villa Alemana",
  "Viña del Mar",
  "Acheng",
  "Akeshu",
  "Aletai",
  "Anda",
  "Anguo",
  "Ankang",
  "Anlu",
  "Anning",
  "Anqing",
  "Anqiu",
  "Anshan",
  "Anshun",
  "Anyang",
  "Atushi",
  "Baicheng",
  "Baise",
  "Baishan",
  "Baiyin",
  "Baoding",
  "Baoji",
  "Baoshan",
  "Baotou",
  "Bazhong",
  "Bazhou",
  "Bei'an",
  "Beihai",
  "BEIJING (PEKING)",
  "Beiliu",
  "Beining",
  "Beipiao",
  "Bengbu",
  "Benxi",
  "Bijie",
  "Binzhou",
  "Bole",
  "Botou",
  "Bozhou",
  "Cangzhou",
  "Cenxi",
  "Changchun",
  "Changde",
  "Changge",
  "Changji",
  "Changle",
  "Changning",
  "Changsha",
  "Changshu",
  "Changyi",
  "Changzhi",
  "Changzhou",
  "Chaohu",
  "Chaoyang (Guangdong)",
  "Chaoyang (Liaoning)",
  "Chaozhou",
  "Chengde",
  "Chengdu",
  "Chenghai",
  "Chenzhou",
  "Chibi",
  "Chifeng",
  "Chishui",
  "Chizhou",
  "Chongqing",
  "Chongzhou",
  "Chuxiong",
  "Chuzhou",
  "Cixi",
  "Conghua",
  "Da'an",
  "Dafeng",
  "Dali",
  "Dalian",
  "Dandong",
  "Dangyang",
  "Danjiangkou",
  "Danyang",
  "Danzhou",
  "Daqing",
  "Dashiqiao",
  "Datong",
  "Daye",
  "Dazhou",
  "Dehui",
  "Dengfeng",
  "Dengta",
  "Dengzhou",
  "Dexing",
  "Deyang",
  "Dezhou",
  "Dingzhou",
  "Dongfang",
  "Donggang",
  "Dongguan",
  "Dongsheng",
  "Dongtai",
  "Dongxing",
  "Dongyang",
  "Dongying",
  "Dujiangyan",
  "Dunhua",
  "Dunhuang",
  "Duyun",
  "Emeishan",
  "Enping",
  "Enshi",
  "Ezhou",
  "Fangchenggang",
  "Feicheng",
  "Fengnan",
  "Fengcheng (Jiangxi)",
  "Fengcheng (Liaoning)",
  "Fenghua",
  "Fengzhen",
  "Fenyang",
  "Foshan",
  "Fu'an",
  "Fuding",
  "Fujin",
  "Fukang",
  "Fuqing",
  "Fuquan",
  "Fushun",
  "Fuxin",
  "Fuyang (Anhui)",
  "Fuyang (Zhejiang)",
  "Fuzhou (Fujian)",
  "Fuzhou (Jiangxi)",
  "Gaizhou",
  "Ganzhou",
  "Gaoan",
  "Gaobeidian",
  "Gaocheng",
  "Gaomi",
  "Gaoming",
  "Gaoping",
  "Gaoyao",
  "Gaoyou",
  "Gaozhou",
  "Geermu",
  "Gejiu",
  "Genhe",
  "Gongyi",
  "Gongzhuling",
  "Guangan",
  "Guanghan",
  "Guangshui",
  "Guangyuan",
  "Guangzhou",
  "Guigang",
  "Guilin",
  "Guiping",
  "Guixi",
  "Guiyang",
  "Gujiao",
  "Haerbin",
  "Haicheng",
  "Haikou",
  "Hailaer",
  "Hailin",
  "Hailun",
  "Haimen",
  "Haining",
  "Haiyang",
  "Hami",
  "Hancheng",
  "Hanchuan",
  "Handan",
  "Hangzhou",
  "Hanzhong",
  "Hebi",
  "Hechi",
  "Hechuan",
  "Hefei",
  "Hegang",
  "Heihe",
  "Hejian",
  "Hejin",
  "Helong",
  "Hengshui",
  "Hengyang",
  "Heshan (Guangdong)",
  "Heshan (Guangxi)",
  "Hetian",
  "Heyuan",
  "Heze",
  "Hezhou",
  "Honghu",
  "Hongjiang",
  "Houma",
  "Huadian",
  "Huaian",
  "Huaibei",
  "Huaihua",
  "Huainan",
  "Huaiyin",
  "Huanggang",
  "Huanghua",
  "Huangshan",
  "Huangshi (Hubei)",
  "Huayin",
  "Huaying",
  "Huazhou",
  "Huhehaote",
  "Huixian",
  "Huiyang",
  "Huizhou",
  "Hulin",
  "Huludao",
  "Hunchun",
  "Huozhou",
  "Huzhou",
  "Jiamusi",
  "Ji'an (Jiangxi)",
  "Jian (Jilin)",
  "Jiande",
  "Jiangdu",
  "Jiangjin",
  "Jiangmen",
  "Jiangshan",
  "Jiangyan",
  "Jiangyin",
  "Jiangyou",
  "Jianou",
  "Jianyang (Fujian)",
  "Jianyang (Sichuan)",
  "Jiaohe",
  "Jiaonan",
  "Jiaozhou",
  "Jiaozuo",
  "Jiaxing",
  "Jiayuguan",
  "Jieshou",
  "Jiexiu",
  "Jieyang",
  "Jilin",
  "Jimo",
  "Jinan",
  "Jinchang",
  "Jincheng",
  "Jingdezhen",
  "Jinggangshan",
  "Jinghong",
  "Jingjiang",
  "Jingmen",
  "Jingzhou",
  "Jinhua",
  "Jining (Inner Mongolia)",
  "Jining (Shandong)",
  "Jinjiang",
  "Jinshi",
  "Jintan",
  "Jinzhong",
  "Jinzhou (Hebei)",
  "Jinzhou (Liaoning)",
  "Jishou",
  "Jiujiang",
  "Jiuquan",
  "Jiutai",
  "Jixi",
  "Jiyuan",
  "Jizhou",
  "Jurong",
  "Kaifeng",
  "Kaili",
  "Kaiping",
  "Kaiyuan (Liaoning)",
  "Kaiyuan (Yunnan)",
  "Kashi (Xinjiang)",
  "Kelamayi",
  "Kuerle",
  "Kuitun",
  "Kunming",
  "Kunshan",
  "Laiwu",
  "Laixi",
  "Laiyang",
  "Laizhou",
  "Langfang",
  "Langzhong",
  "Lanxi",
  "Lanzhou",
  "Laohekou",
  "Lasa",
  "Lechang",
  "Leiyang",
  "Leizhou",
  "Leling",
  "Lengshuijiang",
  "Leping",
  "Leqing",
  "Leshan",
  "Lianjiang",
  "Lianyuan",
  "Lianyungang",
  "Lianzhou",
  "Liaocheng",
  "Liaoyang",
  "Liaoyuan",
  "Lichuan",
  "Liling",
  "Linan",
  "Linfen",
  "Lingbao",
  "Linghai",
  "Lingwu",
  "Lingyuan",
  "Linhai",
  "Linhe",
  "Linjiang",
  "Linqing",
  "Linxia",
  "Linxiang",
  "Linyi",
  "Linzhou",
  "Lishi",
  "Lishui",
  "Lu'an",
  "Liupanshui",
  "Liuyang",
  "Liuzhou",
  "Liyang",
  "Longhai",
  "Longjing",
  "Longkou",
  "Longquan",
  "Longyan",
  "Loudi",
  "Lucheng",
  "Lufeng",
  "Luoding",
  "Luohe",
  "Luoyang",
  "Luquan",
  "Luxi (Yunnan)",
  "Luzhou",
  "Ma'anshan",
  "Macheng",
  "Manzhouli",
  "Maoming",
  "Meihekou",
  "Meishan",
  "Meizhou",
  "Mianyang",
  "Mianzhu",
  "Miluo",
  "Mingguang",
  "Miquan",
  "Mishan",
  "Mudanjiang",
  "Muling",
  "Nanan",
  "Nanchang",
  "Nanchong",
  "Nanchuan",
  "Nangong",
  "Nanhai",
  "Nanjing",
  "Nankang",
  "Nanning",
  "Nanping",
  "Nantong",
  "Nanxiong",
  "Nanyang",
  "Nehe",
  "Neijiang",
  "Ningan",
  "Ningbo",
  "Ningde",
  "Ningguo",
  "Panjin",
  "Panshi",
  "Panzhihua",
  "Penglai",
  "Pengzhou",
  "Pingdingshan",
  "Pingdu",
  "Pinghu",
  "Pingliang",
  "Pingxiang (Guangxi)",
  "Pingxiang (Jiangxi)",
  "Pizhou",
  "Pulandian",
  "Puning",
  "Putian",
  "Puyang",
  "Qianan",
  "Qianjiang",
  "Qidong",
  "Qingdao",
  "Qingtongxia",
  "Qingyuan",
  "Qingzhen",
  "Qingzhou",
  "Qinhuangdao",
  "Qinyang",
  "Qinzhou",
  "Qionghai",
  "Qionglai",
  "Qiongshan",
  "Qiqihaer",
  "Qitaihe",
  "Qixia",
  "Quanzhou",
  "Qufu",
  "Qujing",
  "Quzhou",
  "Renhuai",
  "Renqiu",
  "Rizhao",
  "Rongcheng",
  "Rugao",
  "Ruian",
  "Ruichang",
  "Ruijin",
  "Ruili",
  "Rushan",
  "Ruzhou",
  "Sanhe",
  "Sanmenxia",
  "Sanming",
  "Sanshui",
  "Sanya",
  "Shahe",
  "Shanghai",
  "Shangqiu",
  "Shangrao",
  "Shangyu",
  "Shangzhi",
  "Shangzhou",
  "Shantou",
  "Shanwei",
  "Shaoguan",
  "Shaowu",
  "Shaoxing",
  "Shaoyang",
  "Shengzhou",
  "Shenyang",
  "Shenzhen",
  "Shenzhou",
  "Shifang",
  "Shihezi",
  "Shijiazhuang",
  "Shishi",
  "Shishou",
  "Shiyan",
  "Shizuishan",
  "Shouguang",
  "Shuangcheng",
  "Shuangliao",
  "Shuangyashan",
  "Shulan",
  "Shunde",
  "Shuozhou",
  "Sihui",
  "Simao",
  "Siping",
  "Songyuan",
  "Songzi",
  "Suihua",
  "Suining",
  "Suizhou",
  "Suqian",
  "Suzhou (Anhui)",
  "Suzhou (Jiangsu)",
  "Tacheng",
  "Tai'an",
  "Taicang",
  "Taishan",
  "Taixing",
  "Taiyuan",
  "Taizhou (Jiangsu)",
  "Taizhou (Zhejiang)",
  "Tangshan",
  "Taonan",
  "Tengzhou",
  "Tianchang",
  "Tianjin",
  "Tianmen",
  "Tianshui",
  "Tiefa",
  "Tieli",
  "Tieling",
  "Tongcheng",
  "Tongchuan",
  "Tonghua",
  "Tongjiang",
  "Tongliao",
  "Tongling",
  "Tongren",
  "Tongshi",
  "Tongxiang",
  "Tongzhou",
  "Tulufan",
  "Tumen",
  "Urumqi",
  "Wafangdian",
  "Wanning",
  "Wanyuan",
  "Weifang",
  "Weihai",
  "Weihui",
  "Weinan",
  "Wenchang",
  "Wendeng",
  "Wenling",
  "Wenzhou",
  "Wuan",
  "Wuchang",
  "Wuchuan",
  "Wudalianchi",
  "Wugang (Henan)",
  "Wugang (Hunan)",
  "Wuhai",
  "Wuhan",
  "Wuhu",
  "Wujiang",
  "Wujin",
  "Wulanhaote",
  "Wusu",
  "Wuwei",
  "Wuxi",
  "Wuxian",
  "Wuxue",
  "Wuyishan",
  "Wuzhong",
  "Wuzhou",
  "Xiamen",
  "Xi'an",
  "Xiangcheng",
  "Xiangfan",
  "Xiangtan",
  "Xiangxiang",
  "Xianning",
  "Xiantao",
  "Xianyang",
  "Xiaogan",
  "Xiaoshan",
  "Xiaoyi",
  "Xichang",
  "Xifeng",
  "Xilinhaote",
  "Xingcheng",
  "Xinghua",
  "Xingning",
  "Xingping",
  "Xingtai",
  "Xingyang",
  "Xingyi",
  "Xinhui",
  "Xining",
  "Xinji",
  "Xinle",
  "Xinmi",
  "Xinmin",
  "Xintai",
  "Xinxiang",
  "Xinyang",
  "Xinyi (Guangdong)",
  "Xinyi (Jiangsu)",
  "Xinyu",
  "Xinzheng",
  "Xinzhou",
  "Xishan",
  "Xuancheng",
  "Xuanwei",
  "Xuchang",
  "Xuzhou",
  "Ya'an",
  "Yakeshi",
  "Yan'an",
  "Yancheng",
  "Yangchun",
  "Yangjiang",
  "Yangquan",
  "Yangzhong",
  "Yangzhou",
  "Yanji",
  "Yanshi",
  "Yantai",
  "Yibin",
  "Yichang",
  "Yicheng",
  "Yichun (Heilongjiang)",
  "Yichun (Jiangxi)",
  "Yidu",
  "Yima",
  "Yinchuan",
  "Yingcheng",
  "Yingde",
  "Yingko",
  "Yingtan",
  "Yining",
  "Yiwu",
  "Yixing",
  "Yiyang",
  "Yizheng",
  "Yizhou",
  "Yongan",
  "Yongcheng",
  "Yongchuan",
  "Yongji",
  "Yongkang",
  "Yongzhou",
  "Yuanjiang",
  "Yuanping",
  "Yucheng",
  "Yueyang",
  "Yuhang",
  "Yulin (Guangxi)",
  "Yulin (Shaanxi)",
  "Yumen",
  "Yuncheng",
  "Yunfu",
  "Yanzhou",
  "Yushu",
  "Yuxi",
  "Yuyao",
  "Yuzhou",
  "Zaoyang",
  "Zaozhuang",
  "Zengcheng",
  "Zhalantun",
  "Zhangjiagang",
  "Zhangjiajie",
  "Zhangjiakou",
  "Zhangping",
  "Zhangqiu",
  "Zhangshu",
  "Zhangye",
  "Zhangzhou",
  "Zhanjiang",
  "Zhaodong",
  "Zhaoqing",
  "Zhaotong",
  "Zhaoyuan",
  "Zhengzhou",
  "Zhenjiang",
  "Zhijiang",
  "Zhongshan",
  "Zhongxiang",
  "Zhoukou",
  "Zhoushan",
  "Zhuanghe",
  "Zhucheng",
  "Zhuhai",
  "Zhuji",
  "Zhumadian",
  "Zhuozhou",
  "Zhuzhou",
  "Zibo",
  "Zigong",
  "Zixing",
  "Ziyang",
  "Zoucheng",
  "Zunhua",
  "Zunyi",
  "HONG KONG SAR",
  "MACAO",
  "Apartadó",
  "Armenia",
  "Barrancabermeja",
  "Barranquilla",
  "Bello",
  "Bucaramanga",
  "Buenaventura",
  "Cali",
  "Cartagena",
  "Cartago",
  "Ciénaga",
  "Cúcuta",
  "Dosquebradas",
  "Duitama",
  "Envigado",
  "Facatativá",
  "Florencia",
  "Floridablanca",
  "Fusagasugá",
  "Girón",
  "Gudalajara de Buga",
  "Ibagué",
  "Ipiales",
  "Itagüi",
  "Lorica",
  "Magangué",
  "Maicao",
  "Manizales",
  "Medellín",
  "Montería",
  "Neiva",
  "Palmira",
  "Pasto",
  "Pereira",
  "Piedecuesta",
  "Pitalito",
  "Popayán",
  "Quibdo",
  "Riohacha",
  "Rionegro",
  "San Andres de Tumaco",
  "BOGOTA, D.C.",
  "Santa Marta",
  "Sincelejo",
  "Soacha",
  "Sogamoso",
  "Soledad",
  "Tuluá",
  "Tunja",
  "Turbo",
  "Uribia",
  "Valledupar",
  "Villavicencio",
  "Yopal",
  "Zipaquirá",
  "MORONI",
  "BRAZZAVILLE",
  "Pointe-Noire",
  "RAROTONGA",
  "Alajuela",
  "Alajuelita",
  "Desamparados",
  "Goicoechea",
  "Heredia",
  "La Unión",
  "Limón",
  "Pavas",
  "Perez Zeledon",
  "Puntarenas",
  "San Carlos",
  "SAN JOSE",
  "Pococi",
  "Abidjan",
  "Bouake",
  "Daloa",
  "Korhogo",
  "YAMOUSSOUKRO",
  "Osijek",
  "Rijeka",
  "Split",
  "ZAGREB",
  "Bayamo",
  "Camagüey",
  "Ciego de Avila",
  "Cienfuegos",
  "Guantánamo",
  "Holguín",
  "LA HABANA",
  "Las Tunas",
  "Matanzas",
  "Pinar del Río",
  "Sancti Spíritus",
  "Santa Clara",
  "Santiago de Cuba",
  "Brno",
  "Hradec Králové",
  "Liberec",
  "Olomouc",
  "Ústí nad Labem",
  "Ostrava",
  "Plzen",
  "PRAHA",
  "Anju",
  "Chongjin",
  "Haeju",
  "Hamhung",
  "Huichon",
  "Hyesan",
  "Jongju",
  "Kaechon",
  "Kaesong",
  "Kanggye",
  "Kim Chaek",
  "Kusong",
  "Nampho",
  "Phyongsong",
  "PYONGYANG",
  "Rason",
  "Sariwon",
  "Sinuiju",
  "Sinpho",
  "Sunchon",
  "Wonsan",
  "Tanchon",
  "Tokchon",
  "Ålborg",
  "Århus",
  "Esbjerg",
  "Frederiksberg",
  "KOBENHAVN",
  "Odense",
  "Vejle",
  "ROSEAU",
  "Azua",
  "Bajos de Haina",
  "Baní",
  "Boca Chica",
  "Bonao",
  "Higüey",
  "La Romana",
  "Moca",
  "La Vega",
  "Los Alcarrizos",
  "Puerto Plata",
  "San Cristóbal",
  "San Francisco de Macoris",
  "San Juan de la Maguana",
  "San Pedro de Macoris",
  "Santiago de los Caballeros",
  "SANTO DOMINGO",
  "Santo Domingo East",
  "Santo Domingo West",
  "Santo Domingo North",
  "Ambato",
  "Calderon (Carapungo)",
  "Cuenca",
  "Durán",
  "Esmeraldas",
  "Guayaquil",
  "Ibarra",
  "Loja",
  "Machala",
  "Manta",
  "Milagro",
  "Portoviejo",
  "Quevedo",
  "QUITO",
  "Riobamba",
  "Santa Elena",
  "Babahoyo",
  "Santo Domingo de los Colorados",
  "6th of October City",
  "Abo Keber",
  "Akhmim",
  "Alexandria",
  "Assyût",
  "Aswan",
  "Banha",
  "Beni-Suef",
  "Bilbes",
  "CAIRO",
  "Damietta",
  "Damanhûr",
  "El-Aresh",
  "El-Khosos",
  "Desok",
  "El-Hwamdia",
  "El-Mahalla El-Kubra",
  "El-Mataria",
  "Faiyûm",
  "Gerga",
  "Giza",
  "Ismailia",
  "Kafr-El-Dwar",
  "Kaluop",
  "Kena",
  "Luxer",
  "Malawe",
  "Mansûra",
  "Matrouh",
  "Menia",
  "Met Ghamr",
  "Port Said",
  "Ramadan",
  "Shebin-El-Kom",
  "Shubra-El-Khema",
  "Sohag",
  "Suez",
  "Tanta",
  "Zagazig",
  "Al Orizah",
  "Imbaba",
  "Ahuachapan",
  "Apopa",
  "Ciudad Delgado",
  "Ilopango",
  "Mejicanos",
  "Santa Tecla",
  "San Miguel",
  "SAN SALVADOR",
  "Santa Ana",
  "Soyapango",
  "Cuscatancingo",
  "San Martin",
  "Sonsonate",
  "MALABO",
  "ASMARA",
  "TALLINN",
  "Tartu",
  "THORSHAVN",
  "STANLEY",
  "SUVA",
  "Espoo",
  "HELSINKI",
  "Jyvaskyla",
  "Kuopio",
  "Lahti",
  "Oulu",
  "Tampere",
  "Turku",
  "Vantaa",
  "Aix-en-Provence",
  "Amiens",
  "Angers",
  "Argenteuil",
  "Besançon",
  "Bordeaux",
  "Boulogne-Billancourt",
  "Caen",
  "Clermont-Ferrand",
  "Dijon",
  "Grenoble",
  "Le Havre",
  "Le Mans",
  "Lille",
  "Limoges",
  "Lyon",
  "Marseille",
  "Metz",
  "Montpellier",
  "Montreuil",
  "Mulhouse",
  "Nancy",
  "Nantes",
  "Nice",
  "Nîmes",
  "Orléans",
  "PARIS",
  "Perpignan",
  "Reims",
  "Rennes",
  "Rouen",
  "Saint-Denis",
  "Saint-Étienne",
  "Strasbourg",
  "Toulon",
  "Toulouse",
  "Tours",
  "Villeurbanne",
  "Saint-Denis (La Réunion)",
  "Saint-Paul (La Réunion)",
  "CAYENNE",
  "PAPEETE",
  "LIBREVILLE",
  "BANJU",
  "Batumi",
  "Kutaisi",
  "Rustavi",
  "TBILISI",
  "Aachen",
  "Augsburg",
  "Bergisch Gladbach",
  "BERLIN",
  "Bielefeld",
  "Bochum",
  "Bonn",
  "Bottrop",
  "Braunschweig",
  "Bremen",
  "Bremerhaven",
  "Chemnitz",
  "Darmstadt",
  "Dortmund",
  "Dresden",
  "Duisburg",
  "Düsseldorf",
  "Erfurt",
  "Erlangen",
  "Essen",
  "Frankfurt am Main",
  "Freiburg im Breisgau",
  "Fürth",
  "Gelsenkirchen",
  "Göttingen",
  "Hagen",
  "Halle",
  "Hamburg",
  "Hamm",
  "Hannover",
  "Heidelberg",
  "Heilbronn",
  "Herne",
  "Ingolstadt",
  "Jena",
  "Karlsruhe",
  "Kassel",
  "Kiel",
  "Koblenz",
  "Köln",
  "Krefeld",
  "Leipzig",
  "Leverkusen",
  "Lübeck",
  "Ludwigshafen am Rhein",
  "Magdeburg",
  "Mainz",
  "Mannheim",
  "Moers",
  "Mönchengladbach",
  "Mülheim an der Ruhr",
  "München",
  "Münster (Westf.)",
  "Neuss",
  "Nürnberg",
  "Oberhausen",
  "Offenbach am Main",
  "Oldenburg",
  "Osnabrück",
  "Paderborn",
  "Pforzheim",
  "Potsdam",
  "Recklinghausen",
  "Regensburg",
  "Remscheid",
  "Reutlingen",
  "Rostock",
  "Saarbrücken",
  "Solingen",
  "Stuttgart",
  "Trier",
  "Ulm",
  "Wiesbaden",
  "Wolfsburg",
  "Wuppertal",
  "Würzburg",
  "Cottbus",
  "Hildesheim",
  "Salzgitter",
  "Siegen",
  "Gera",
  "Kaiserslautern",
  "Schwerin",
  "Witten",
  "Zwickau",
  "ACCRA",
  "Kumasi",
  "Sekondi",
  "Takoradi",
  "Tamale",
  "Tema",
  "GIBRALTAR",
  "ATHINAI",
  "Calithèa",
  "Iraclion",
  "Larissa",
  "Patrai",
  "Pésterion",
  "Pireas",
  "Thessaloniki",
  "NUUK (GODTHAB)",
  "ST. GEORGE'S",
  "BASSE-TERRE",
  "Pointe-à-Pitre",
  "AGANA",
  "Escuintla",
  "CUIDAD DE GUATEMALA",
  "Mixco",
  "Quetzaltenango",
  "Villa Nueva",
  "ST. PETER PORT",
  "CONAKRY",
  "Kankan",
  "Kindia",
  "Labé",
  "Nzérékoré",
  "BISSAU",
  "GEORGETOWN",
  "VATICAN CITY",
  "Choloma",
  "La Ceiba",
  "San Pedro Sula",
  "TEGUCIGALPA",
  "BUDAPEST",
  "Debrecen",
  "Györ",
  "Kecskemét",
  "Miskolc",
  "Nyiregyhaza",
  "Pécs",
  "Szeged",
  "Székesfehérvar",
  "REYKJAVIK",
  "Abohar",
  "Achalpur",
  "Adilabad",
  "Adityapur",
  "Adoni",
  "Agartala",
  "Agra",
  "Ahmedabad",
  "Ahmednagar",
  "Aizawl",
  "Ajmer",
  "Akola",
  "Alandur",
  "Alappuzha",
  "Aligarh",
  "Alipurduar",
  "Allahabad",
  "Alwar",
  "Ambala",
  "Ambala Sadar",
  "Ambarnath",
  "Ambattur",
  "Amravati",
  "Amritsar",
  "Amroha",
  "Anand",
  "Anantapur",
  "Anklesvar",
  "Arcot",
  "Arrah",
  "Asansol",
  "Ashoknagar Kalyangarh",
  "Aurangabad",
  "Avadi",
  "Bahadurgarh",
  "Baharampur",
  "Bahraich",
  "Baidyabati",
  "Baleshwar",
  "Ballia",
  "Bally",
  "Balurghat",
  "Banda",
  "Bangalore",
  "Bangaon",
  "Bankura",
  "Bansberia",
  "Baranagar",
  "Barasat",
  "Barddhaman",
  "Bareilly",
  "Baripada",
  "Barrackpur",
  "Barshi",
  "Basirhat",
  "Basti",
  "Batala",
  "Bathinda",
  "Beawar",
  "Begusarai",
  "Belgaum",
  "Bellary",
  "Bettiah",
  "Bhadravati",
  "Bhadreswar",
  "Bhagalpur",
  "Bhalswa Jahangir Pur",
  "Bharatpur",
  "Bharuch",
  "Bhatpara",
  "Bhavani",
  "Bhavnagar",
  "Bheemavaram",
  "Bhilai Nagar",
  "Bhilwara",
  "Bhind",
  "Bhiwandi",
  "Bhiwani",
  "Bhopal",
  "Bhubaneswar",
  "Bhuj",
  "Bhusawal",
  "Bid",
  "Bidar",
  "Bidhan Nagar",
  "Bihar",
  "Bijapur",
  "Bikaner",
  "Bilaspur",
  "Birnagar",
  "Bokaro Steel City",
  "Bommanahalli",
  "Botad",
  "Brahmapur",
  "Budaun",
  "Bulandshahr",
  "Burhanpur",
  "Byatarayanapura",
  "Chakdaha",
  "Champdani",
  "Chandan Nagar",
  "Chandausi",
  "Chandigarh",
  "Chandrapur",
  "Chapra",
  "Chennai (Madras)",
  "Cherthala",
  "Chhatarpur",
  "Chhindwara",
  "Chikmagalur",
  "Chirala",
  "Chirkunda",
  "Chitradurga",
  "Chittoor",
  "Churu",
  "Coimbatore",
  "Coonoor",
  "Cuddalore",
  "Cuddapah",
  "Cuttack",
  "Dallo Pura",
  "Damoh",
  "Darbhanga",
  "Darjiling",
  "Dasarahalli",
  "Davangere",
  "Dehradun",
  "Dehri",
  "Delhi",
  "Delhi Cantonment",
  "Deoghar",
  "Deoli",
  "Deoria",
  "Dewas",
  "Dhanbad",
  "Dharmavaram",
  "Dhule",
  "Dibrugarh",
  "Dinapur Nizamat",
  "Dindigul",
  "Dohad",
  "Dumdum",
  "Durg",
  "Durgapur",
  "Durg-Bhilai Nagar",
  "Eluru",
  "English Bazar",
  "Erode",
  "Etah",
  "Etawah",
  "Faizabad",
  "Faridabad",
  "Farrukhabad-cum-Fategarh",
  "Fatehpur",
  "Firozabad",
  "Gadag-Betgeri",
  "Gajuwaka",
  "Gandhidham",
  "Gandhinagar",
  "Ganganagar",
  "Gangawati",
  "Gaya",
  "Ghatlodiya",
  "Ghaziabad",
  "Ghazipur",
  "Giridih",
  "Godhra",
  "Gonda",
  "Gondiya",
  "Gorakhpur",
  "Gudivada",
  "Gudiyatham",
  "Gulbarga",
  "Guna",
  "Guntakul",
  "Guntur",
  "Gurgaon",
  "Guruvayur",
  "Guwahati",
  "Gwalior",
  "Habra",
  "Hajipur",
  "Haldia",
  "Haldwani-cum-Kathgodam",
  "Halisahar",
  "Hanumangarh",
  "Haora (Howrah)",
  "Hapur",
  "Hardoi",
  "Hardwar",
  "Hassan",
  "Hathras",
  "Hazaribag",
  "Hindupur",
  "Hisar",
  "Hoshiarpur",
  "Hospet",
  "Hubli-Dharwad",
  "Hugli-Chinsurah",
  "Hyderabad",
  "Ichalakaranji",
  "Imphal",
  "Indore",
  "Itarsi",
  "Jabalpur",
  "Jagadhri",
  "Jagdalpur",
  "Jaipur",
  "Jalandhar",
  "Jalgaon",
  "Jalna",
  "Jalpaiguri",
  "Jammu",
  "Jamnagar",
  "Jamshedpur",
  "Jamuria",
  "Jaunpur",
  "Jetpur Navagadh",
  "Jhansi",
  "Jhunjhunun",
  "Jind",
  "Jodhpur",
  "Jorhat",
  "Junagadh",
  "Kaithal",
  "Kakinada",
  "Kalol",
  "Kalyan",
  "Kamarhati",
  "Kamptee",
  "Kancheepuram",
  "Kanchrapara",
  "Kanhangad",
  "Kannur",
  "Kanpur",
  "Kapra",
  "Karaikkudi",
  "Karawal Nagar",
  "Karimnagar",
  "Karnal",
  "Karur",
  "Katihar",
  "Khammam",
  "Khandwa",
  "Khanna",
  "Kharagpur",
  "Khardaha",
  "Khargone",
  "Kirari Suleman Nagar",
  "Kishangarh",
  "Koch Bihar",
  "Kochi",
  "Kolar",
  "Kolhapur",
  "Kolkata (Calcutta)",
  "Kollam",
  "Korba",
  "Kota",
  "Kothagudem",
  "Kottayam",
  "Kozhikode",
  "Krishnanagar",
  "Krishnarajapura",
  "Kukatpalle",
  "Kulti",
  "Kumbakonam",
  "Kurnool",
  "Lal Bahadur Nagar",
  "Lakhimpur",
  "Lalitpur",
  "Latur",
  "Loni",
  "Lucknow",
  "Ludhiana",
  "Machilipatnam",
  "Madanapalle",
  "Madhyamgram",
  "Madurai",
  "Mahadevapura",
  "Mahbubnagar",
  "Mahesana",
  "Maheshtala",
  "Mainpuri",
  "Malappuram",
  "Malegaon",
  "Malerkotla",
  "Malkajgiri",
  "Mancherial",
  "Mandsaur",
  "Mandya",
  "Mangalore",
  "Mango",
  "Mathura",
  "Maunath Bhanjan",
  "Medinipur",
  "Meerut",
  "Mira-Bhayandar",
  "Mirzapur-cum-Vindhyachal",
  "Modinagar",
  "Moga",
  "Moradabad",
  "Morena",
  "Mormugoa",
  "Morvi",
  "Motihari",
  "Mughalsarai",
  "Mumbai (Bombay)",
  "Munger",
  "Murwara (Katni)",
  "Muzaffarnagar",
  "Muzaffarpur",
  "Mysore",
  "Nabadwip",
  "Nadiad",
  "Nagaon",
  "Nagercoil",
  "Nagpur",
  "Naihati",
  "Nala Sopara",
  "Nalgonda",
  "Nanded",
  "Nandyal",
  "Nangloi Jat",
  "Nashik",
  "Navghar-Manikpur",
  "Navi Mumbai (New Bombay)",
  "Navsari",
  "Neemuch",
  "Nellore",
  "NEW DELHI",
  "Neyveli",
  "Nizamabad",
  "Noida",
  "North Barrackpur",
  "North Dumdum",
  "Ongole",
  "Orai",
  "Ozhukarai",
  "Palakkad",
  "Palanpur",
  "Pali",
  "Pallavaram",
  "Palwal",
  "Panchkula Urban Estate",
  "Panihati",
  "Panipat",
  "Panvel",
  "Parbhani",
  "Patan",
  "Pathankot",
  "Patiala",
  "Patna",
  "Phagwara",
  "Phusro",
  "Pilibhit",
  "Pimpri Chinchwad",
  "Pollachi",
  "Pondicherry",
  "Porbandar",
  "Proddatur",
  "Pudukkottai",
  "Pune",
  "Puri",
  "Purnia",
  "Puruliya",
  "Quthbullapur",
  "Rae Bareli",
  "Raichur",
  "Raiganj",
  "Raigarh",
  "Raipur",
  "Rajahmundry",
  "Rajapalayam",
  "Rajarhat Gopalpur",
  "Rajendranagar",
  "Rajkot",
  "Rajnandgaon",
  "Rajpur Sonarpur",
  "Ramagundam",
  "Ramgarh",
  "Rampur",
  "Ranaghat",
  "Ranchi",
  "Raniganj",
  "Ratlam",
  "Raurkela",
  "Raurkela Industrialship",
  "Rewa",
  "Rewari",
  "Rishra",
  "Robertson Pet",
  "Rohtak",
  "Roorkee",
  "S.A.S. Nagar (Mohali)",
  "Sagar",
  "Saharanpur",
  "Saharasa",
  "Salem",
  "Sambalpur",
  "Sambhal",
  "Sangli-Miraj-Kupwad",
  "Santipur",
  "Sasaram",
  "Satara",
  "Satna",
  "Sawai Madhopur",
  "Secunderabad",
  "Serampore",
  "Serilingampalle",
  "Shahjahanpur",
  "Shillong",
  "Shimla",
  "Shimoga",
  "Shivapuri",
  "Sikar",
  "Silchar",
  "Siliguri",
  "Singrauli",
  "Sirsa",
  "Sitapur",
  "Sivakasi",
  "Siwan",
  "Solapur",
  "Sonipat",
  "South Dum Dum",
  "Srikakulam",
  "Srinagar",
  "Sultan Pur Majra",
  "Sultanpur",
  "Surat",
  "Surendranagar Dudhrej",
  "Tadepalligudem",
  "Tambaram",
  "Tenali",
  "Thane",
  "Thanesar",
  "Thanjavur",
  "Thiruvananthapuram",
  "Thoothukkudi (Tuticorin)",
  "Thrissur",
  "Tinsukia",
  "Tiruchchirappalli",
  "Tirunelveli",
  "Tirupati",
  "Tiruppur",
  "Tiruvannamalai",
  "Tiruvottiyur",
  "Titagarh",
  "Tonk",
  "Tumkur",
  "Udaipur",
  "Udupi",
  "Ujjain",
  "Ulhasnagar",
  "Uluberia",
  "Unnao",
  "Uppal Kalan",
  "Uttarpara Kotrung",
  "Vadakara",
  "Vadodara",
  "Valsad",
  "Vaniyambadi",
  "Varanasi",
  "Vasai",
  "Vejalpur",
  "Vellore",
  "Veraval",
  "Vidisha",
  "Vijayawada",
  "Virar",
  "Visakhapatnam",
  "Vizianagarm",
  "Wadhwan",
  "Warangal",
  "Wardha",
  "Yamunanagar",
  "Yavatmal",
  "Gangapur City",
  "Tezpur",
  "Ambon",
  "Balikpapan",
  "Banda Aceh",
  "Bandar Lampung",
  "Bandjarmasin",
  "Bandung",
  "Batam",
  "Bengkulu",
  "Binjai",
  "Bitung",
  "Blitar",
  "Bogor",
  "Cirebon (Tjirebon)",
  "Denpasar",
  "Gorontalo",
  "JAKARTA",
  "Jambi",
  "Jayapura",
  "Kediri",
  "Madiun",
  "Magelang",
  "Makasar (Ujung Pandang)",
  "Malang",
  "Manado",
  "Mataram",
  "Medan",
  "Mojokerto",
  "Padang",
  "Pakalongan",
  "Pakanbaru",
  "Palangkaraya",
  "Palembang",
  "Pangkal Pinang",
  "Pare Pare",
  "Pasuruan",
  "Pematang Siantar",
  "Pontianak",
  "Probolinggo",
  "Salatiga",
  "Samarinda",
  "Semarang",
  "Sukabumi",
  "Surabaya",
  "Surakarta",
  "Tangerang",
  "Tanjung Balai",
  "Tebing Tinggi",
  "Tegal",
  "Yogyakarta",
  "Abadan",
  "Bam",
  "Ahwaz",
  "Marand",
  "Pakdasht",
  "Quchan",
  "Rafsanjan",
  "Saveh",
  "Semnan",
  "Shahinshahr",
  "Shahreza",
  "Amol",
  "Torbat-e-heydariyeh",
  "Andimeshk",
  "Arak",
  "Ardabil",
  "Babol",
  "Bandar-e-Abbas",
  "Birjand",
  "Bojnurd",
  "Borujerd",
  "Bukand",
  "Bushehr",
  "Dezful",
  "Esfahan",
  "Fasa",
  "Gonbad-e-Kavus",
  "Gorgan",
  "Hamadan",
  "Ilam",
  "Islam Shahr (Qasemabad)",
  "Jiroft",
  "Karaj",
  "Kamal Shahr",
  "Kashan",
  "Kerman",
  "Kermanshah",
  "Khomeini shahr",
  "Khoramabad",
  "Khoramshahr",
  "Khoy",
  "Mahabad",
  "Malayer",
  "Maraqeh",
  "Marivan",
  "Marvadsht",
  "Mashhad",
  "Masjed Soleyman",
  "Mohammad Shahr",
  "Miandoab",
  "Nasim Shahr",
  "Shahriar",
  "Najafabad",
  "Nazar Abad",
  "Neyshabur",
  "Orumiyeh",
  "Qaem shahr",
  "Qarchak",
  "Qazvin",
  "Qods",
  "Qom",
  "Rasht",
  "Sabzewar",
  "Sanandaj",
  "Saqez",
  "Sari",
  "Shahr-e-Kord",
  "Shahrud",
  "Shiraz",
  "Shoosh",
  "Sirjan",
  "Tabriz",
  "TEHRAN",
  "Varamin",
  "Yasooj",
  "Yazd",
  "Zabol",
  "Zahedan",
  "Zanjan",
  "Bandar-e-Anzali",
  "Bandar-e-Mahshahr",
  "Behbahan",
  "Dorud",
  "Golestan (Soltanabad)",
  "Iranshahr",
  "Izeh",
  "Jahrom",
  "Malard",
  "Adhamiyah",
  "Amara",
  "BAGHDAD",
  "Basra",
  "Diwaniya",
  "Erbil",
  "Hilla",
  "Kadhimain",
  "Karradah Sharqiyah",
  "Kerbala",
  "Kirkuk",
  "Kut",
  "Majnoon",
  "Mosul",
  "Najaf",
  "Nasariya",
  "Ramadi",
  "Sulamaniya",
  "Cork",
  "DUBLIN",
  "DOUGLAS",
  "Ashdod",
  "Ashqelon",
  "Bat Yam",
  "Be'er Sheva",
  "Bene Beraq",
  "Haifa",
  "Holon",
  "JERUSALEM",
  "Netanya",
  "Petah Tiqwa",
  "Ramat Gan",
  "Rehovot",
  "Rishon Leziyyon",
  "Tel Aviv-Yafo",
  "Ancona",
  "Bari",
  "Bergamo",
  "Bologna",
  "Bolzano",
  "Brescia",
  "Cagliari",
  "Catania",
  "Ferrara",
  "Firenze",
  "Foggia",
  "Forli",
  "Genova",
  "Giugliano in Campania",
  "Latina",
  "Livorno",
  "Messina",
  "Milano",
  "Modena",
  "Monza",
  "Napoli",
  "Novara",
  "Padova",
  "Palermo",
  "Parma",
  "Perugia",
  "Pescara",
  "Piacenza",
  "Prato",
  "Ravenna",
  "Reggio di Calabria",
  "Reggio nell'Emilia",
  "Rimini",
  "ROMA",
  "Salerno",
  "Sassari",
  "Siracusa",
  "Taranto",
  "Terni",
  "Torino",
  "Trento",
  "Trieste",
  "Venezia",
  "Verona",
  "Vicenza",
  "KINGSTON",
  "Montego Bay",
  "Portmore",
  "Spanish Town",
  "Abiko",
  "Ageo",
  "Aizuwakamatsu",
  "Akashi",
  "Akishima",
  "Akita",
  "Amagasaki",
  "Anjo",
  "Aomori",
  "Asahikawa",
  "Asaka",
  "Ashikaga",
  "Atsugi",
  "Beppu",
  "Chiba",
  "Chigasaki",
  "Chikusei",
  "Chikushino",
  "Chofu",
  "Daito",
  "Ebetsu",
  "Ebina",
  "Fuchu",
  "Fuji",
  "Fujieda",
  "Fujimi",
  "Fujimino",
  "Fujinomiya",
  "Fujisawa",
  "Fukaya",
  "Fukui",
  "Fukuoka",
  "Fukushima",
  "Fukuyama",
  "Funabashi",
  "Gifu",
  "Habikino",
  "Hachinohe",
  "Hachioji",
  "Hadano",
  "Hakodate",
  "Hakusan",
  "Hamamatsu",
  "Hanamaki",
  "Handa",
  "Hatsukaichi",
  "Higashihiroshima",
  "Higashikurume",
  "Higashimurayama",
  "Higashiomi",
  "Higashiosaka",
  "Hikone",
  "Himeji",
  "Hino",
  "Hirakata",
  "Hiratsuka",
  "Hirosaki",
  "Hiroshima",
  "Hitachi",
  "Hitachinaka",
  "Hofu",
  "Ibaraki",
  "Ichihara",
  "Ichikawa",
  "Ichinomiya",
  "Ichinoseki",
  "Iida",
  "Iizuka",
  "Ikeda",
  "Ikoma",
  "Imabari",
  "Inazawa",
  "Iruma",
  "Isahaya",
  "Ise",
  "Isehara",
  "Isesaki",
  "Ishinomaki",
  "Itami",
  "Iwaki",
  "Iwakuni",
  "Iwata",
  "Izumi (Osaka)",
  "Izumisano",
  "Izumo",
  "Joetsu",
  "Kadoma",
  "Kagoshima",
  "Kakamigahara",
  "Kakegawa",
  "Kakogawa",
  "Kamagaya",
  "Kamakura",
  "Kanazawa",
  "Kanoya",
  "Kanuma",
  "Karatsu",
  "Kariya",
  "Kashihara",
  "Kashiwa",
  "Kasuga",
  "Kasugai",
  "Kasukabe",
  "Kawachinagano",
  "Kawagoe",
  "Kawaguchi",
  "Kawanishi",
  "Kawasaki",
  "Kazo",
  "Kirishima",
  "Kiryu",
  "Kisarazu",
  "Kishiwada",
  "Kitakyushu",
  "Kitami",
  "Kobe",
  "Kodaira",
  "Kofu",
  "Koga",
  "Koganei",
  "Kokubunji",
  "Komaki",
  "Komatsu",
  "Konosu",
  "Koriyama",
  "Koshigaya",
  "Kuki",
  "Kumagaya",
  "Kumamoto",
  "Kurashiki",
  "Kure",
  "Kurume",
  "Kusatsu",
  "Kushiro",
  "Kuwana",
  "Kyoto",
  "Machida",
  "Maebashi",
  "Marugame",
  "Matsubara",
  "Matsudo",
  "Matsue",
  "Matsumoto",
  "Matsusaka",
  "Matsuyama",
  "Mihara",
  "Minoh",
  "Misato",
  "Mishima",
  "Mitaka",
  "Mito",
  "Miyakonojo",
  "Miyazaki",
  "Moriguchi",
  "Morioka",
  "Musashino",
  "Nagahama",
  "Nagano",
  "Nagaoka",
  "Nagareyama",
  "Nagasaki",
  "Nagoya",
  "Naha",
  "Nara",
  "Narashino",
  "Narita",
  "Nasushiobara",
  "Neyagawa",
  "Niigata",
  "Niihama",
  "Niiza",
  "Nishinomiya",
  "Nishio",
  "Nishitokyo",
  "Nobeoka",
  "Noda",
  "Numazu",
  "Obihiro",
  "Odawara",
  "Ogaki",
  "Oita",
  "Okayama",
  "Okazaki",
  "Okinawa",
  "Ome",
  "Omuta",
  "Onomichi",
  "Osaka",
  "Osaki",
  "Oshu",
  "Ota",
  "Otaru",
  "Otsu",
  "Oyama",
  "Saga",
  "Sagamihara",
  "Saijo",
  "Saitama",
  "Sakado",
  "Sakai",
  "Sakata",
  "Saku",
  "Sakura",
  "Sanda",
  "Sanjo",
  "Sano",
  "Sapporo",
  "Sasebo",
  "Sayama",
  "Sendai",
  "Seto",
  "Shibata",
  "Shimada",
  "Shimonoseki",
  "Shizuoka",
  "Shunan",
  "Soka",
  "Suita",
  "Suzuka",
  "Tachikawa",
  "Tajimi",
  "Takamatsu",
  "Takaoka",
  "Takarazuka",
  "Takasaki",
  "Takatsuki",
  "Tama",
  "Tochigi",
  "Toda",
  "Tokai",
  "Tokorozawa",
  "Tokushima",
  "TOKYO",
  "Tomakomai",
  "Tondabayashi",
  "Toride",
  "Tottori",
  "Toyama",
  "Toyohashi",
  "Toyokawa",
  "Toyonaka",
  "Toyota",
  "Tsu",
  "Tsuchiura",
  "Tsukuba",
  "Tsuruoka",
  "Tsuyama",
  "Ube",
  "Ueda",
  "Uji",
  "Urasoe",
  "Urayasu",
  "Uruma",
  "Utsunomiya",
  "Wakayama",
  "Yachiyo",
  "Yaizu",
  "Yamagata",
  "Yamaguchi",
  "Yamato",
  "Yao",
  "Yatsushiro",
  "Yokkaichi",
  "Yokohama",
  "Yokosuka",
  "Yonago",
  "Zama",
  "Iga",
  "Satsumasendai",
  "Yokote",
  "Iwatsuki",
  "Muroran",
  "Hoya",
  "Omiya",
  "Shimizu",
  "Tokuyama",
  "Urawa",
  "ST. HELIER",
  "AMMAN",
  "Irbid",
  "Russiefa",
  "Zarqa",
  "Aktau",
  "Aktobe",
  "Almaty",
  "ASTANA",
  "Atirau",
  "Ekibastuz",
  "Karaganda",
  "Koktshetau",
  "Kustanai",
  "Kyzylorda",
  "Pavlodar",
  "Petropavlovsk (Severo- Kazakhstanskaya oblast)",
  "Rudni",
  "Semipalatinsk",
  "Shimkent",
  "Taldykorgan",
  "Taraz",
  "Temirtau",
  "Uralsk",
  "Ust-Kamenogorsk",
  "Eldoret",
  "Garissa",
  "Kikuyu",
  "Kisumu",
  "Mavoko/AthiRiver",
  "Mombasa",
  "NAIROBI",
  "Nakuru",
  "Ngong",
  "Ruiru",
  "Thika",
  "TARAWA",
  "KUWAIT CITY",
  "Jaleeb Al-Shuykh",
  "Salmiya",
  "BISHKEK",
  "Osh",
  "VIENTIANE",
  "Daugavpils",
  "RIGA",
  "BEIRUT",
  "Tripoli",
  "MASERU",
  "MONROVIA",
  "VADUZ",
  "Kaunas",
  "Klaipeda",
  "Panevezhis",
  "Shauliai",
  "VILNIUS",
  "LUXEMBOURG-VILLE",
  "ANTANANARIVO",
  "Antsirabe",
  "Fianarantsoa",
  "Mahajanga",
  "Toamasina",
  "Blantyre City",
  "LILONGWE",
  "Air Itam",
  "Alor Setar",
  "Ampang",
  "Ampang/Ulu Kelang",
  "Balakong",
  "Bandar Maharani",
  "Bandar Penggaram",
  "Bintulu",
  "Bt9 Cheras/Sg Raya/Tmn Suntex",
  "Bukit Mertajam",
  "Butterworth",
  "Gelugor",
  "Georgetown",
  "MB Ipoh",
  "MB Johor Bahru",
  "Kajang dan Sungai Chua",
  "Klang",
  "Kluang",
  "MP Kota Bharu",
  "Kota Kinabalu",
  "KUALA LUMPUR",
  "Kuala Terengganu",
  "Kuantan",
  "Kuching",
  "Kulai",
  "Kulim",
  "Lahad Datu",
  "Melaka",
  "Miri",
  "Pasir Gudang",
  "Petaling Jaya",
  "Sandakan",
  "Sekudai",
  "Seleyang Baru",
  "Seremban",
  "Shah Alam",
  "Sibu",
  "Subang Jaya",
  "Sungai Ara",
  "Sungai Petani",
  "Taiping",
  "Tawau",
  "MALÉ",
  "VALLETTA",
  "MAJURO",
  "FORT-DE-FRANCE",
  "NOUAKCHOTT",
  "Beau Bassin - Rose Hill",
  "PORT LOUIS",
  "Vacoas - Phoenix",
  "Acapulco (de Juárez)",
  "Acayucan",
  "Aguascalientes",
  "Apizaco",
  "Campeche",
  "Cancun",
  "Celaya",
  "Chalco de Diaz Covarrubias",
  "Chetumal",
  "Chicoloapán de Juárez",
  "Chihuahua",
  "Chilpacingo (de los Bravo)",
  "Chimalhuacan",
  "Ciudad Acuña",
  "Ciudad Apodaca",
  "Ciudad de Villa de Alvárez",
  "Ciudad Del Carmen",
  "Ciudad General Escobedo",
  "Ciudad Juárez",
  "Ciudad López Mateos",
  "Ciudad Madero",
  "Ciudad Obregón",
  "Ciudad Santa Catarina",
  "Ciudad Valles",
  "Ciudad Victoria",
  "Coatzacoalcos",
  "Colimas",
  "Cuauhtemoc",
  "Cuautitlan Izcalli",
  "Cuautla",
  "Cuernavaca",
  "Culiacán Rosales",
  "Delicias",
  "Durango (Victoria de Durango)",
  "Ecatepec (de Morelos)",
  "Ensenada",
  "Fresnillo",
  "Gómez Palacio",
  "Guadalajara",
  "Guadalupe, Nuevo León",
  "Guadalupe, Zacatecas",
  "Guanajuato",
  "Heroica Guaymas",
  "Hermosillo",
  "Hidalgo del Parral",
  "Iguala (de la Independencia)",
  "Irapuato",
  "Ixtapaluca",
  "Jiutepec",
  "Juárez",
  "La Paz, Distrito Federal",
  "La Paz, Baja California Sur",
  "La Piedad",
  "Lázaro Cárdenas",
  "León (de los Aldama)",
  "Los Mochis",
  "Manzanillo",
  "Matamoros",
  "Mazatlán",
  "Mérida",
  "Mexicali",
  "MEXICO, CIUDAD DE",
  "Minatitlán",
  "Monclova",
  "Monterrey",
  "Morelia",
  "Moroleón - Uriangato",
  "Naucalpan de Juárez",
  "Navojoa",
  "Netzahualcóyotl",
  "Heroica Nogales",
  "Nuevo Laredo",
  "Oaxaca de Juárez",
  "Ocotlán",
  "Orizaba",
  "Pachuca (de Soto)",
  "Piedras Negras",
  "Playa del Carmen",
  "Poza Rica de Hidalgo",
  "Puebla de Zaragoza",
  "Puerto Vallarta",
  "Querétaro",
  "Reynosa",
  "Rioverde - Ciudad Fernández",
  "Salamanca",
  "Saltillo",
  "San Cristobal de las Casas",
  "San Francisco Coacalco",
  "San Francisco del Rincón",
  "San Juan Bautista Tuxtepec",
  "San Juan del Río",
  "San Luis Potosí",
  "San Luis Rio Colorado",
  "San Martín Texmelucan",
  "San Nicolas de los Garza",
  "San Pedro Garza Garcia",
  "Soledad de Graciano Sanchez",
  "Tampico",
  "Tapachula (de Cordova y Ordoñez)",
  "Tecomán",
  "Tehuacán",
  "Tepic",
  "Tijuana",
  "Tlalnepantla",
  "Tlaquepaque",
  "Tlaxcala",
  "Toluca (de Lerdo)",
  "Tonala",
  "Torreón",
  "Tula, Tula de Allende",
  "Tulancingo, Tulancingo de Bravo",
  "Tuxpan",
  "Tuxtla Gutiérrez",
  "Uruapan",
  "Veracruz",
  "Villa Nicolas Romero",
  "Villahermosa",
  "Xalapa-Enriquez",
  "Xico",
  "Zacatecas",
  "Zamora de Hidalgo",
  "Zapopan",
  "PALIKIR",
  "MONACO",
  "Hovsgol",
  "Ovorhangay",
  "ULAANBAATAR",
  "PODGORICA",
  "PLYMOUTH",
  "Beira",
  "Chimoio",
  "MAPUTO",
  "Matola",
  "Mocuba",
  "Nacala",
  "Nampula",
  "Quelimane",
  "Tete",
  "Pathein",
  "Mandalay",
  "Monywa",
  "Mawlamyine",
  "NAY PYI TAW",
  "Bago",
  "Dawei",
  "Ha Ka",
  "Hpa-an",
  "Loikaw",
  "Magway",
  "Myitkyina",
  "Sittway",
  "Taunggyi",
  "Yangon",
  "WINDHOEK",
  "YAREN",
  "Bhimdutta",
  "Biratnagar",
  "Birgunj",
  "Butwal",
  "Dhangadhi",
  "Dharan",
  "KATHMANDU",
  "Pokhara",
  "Almere",
  "Amersfoort",
  "AMSTERDAM",
  "Apeldoorn",
  "Arnhem",
  "Breda",
  "Dordrecht",
  "Ede",
  "Eindhoven",
  "Emmen",
  "Enschede",
  "Geleen-Sittard",
  "Groningen",
  "Haarlem",
  "Haarlemmermeer",
  "Heerlen-Kerkrade",
  "Leiden",
  "Maastricht",
  "Nijmegen",
  "Rotterdam",
  "s-Gravenhage",
  "s-Hertogenbosch",
  "The Hague",
  "Tilburg",
  "Utrecht",
  "Zaanstad",
  "Zoetermeer",
  "Zwolle",
  "NOUMEA",
  "Auckland",
  "Christchurch",
  "Dunedin",
  "Lower Hutt",
  "Napier-Hastings",
  "Tauranga",
  "WELLINGTON",
  "Manukau",
  "North Shore",
  "Waitakere",
  "León",
  "MANAGUA",
  "Maradi",
  "NIAMEY",
  "Zinder",
  "Aba",
  "Abeokuta",
  "ABUJA",
  "Ado-Ekiti",
  "Akure",
  "Awka",
  "Bauchi",
  "Benin City",
  "Bida",
  "Calabar",
  "Damaturu",
  "Effon-Alaiye",
  "Enugu",
  "Gboko",
  "Gombe",
  "Gusau",
  "Ibadan",
  "Ife",
  "Ijebu-Ode",
  "Ikare",
  "Ikire",
  "Ikorodu",
  "Ikot Ekpene",
  "Ilawe-Ekiti",
  "Ilesha",
  "Ilorin",
  "Iseyin",
  "Iwo",
  "Jimeta",
  "Jos",
  "Kaduna",
  "Kano",
  "Katsina",
  "Lagos",
  "Maiduguri",
  "Makurdi",
  "Minna",
  "Mubi",
  "Nnewi",
  "Ogbomosho",
  "Okene",
  "Okpogho",
  "Ondo",
  "Onitsha",
  "Oshogbo",
  "Owerri",
  "Owo",
  "Oyo",
  "Port Harcourt",
  "Sagamu",
  "Sango Otta",
  "Sapele",
  "Sokoto",
  "Suleja",
  "Ugep",
  "Umuahia",
  "Warri",
  "Zaria",
  "ALOFI",
  "GARAPAN",
  "Bergen",
  "OSLO",
  "Stavanger",
  "Trondheim",
  "As Seeb",
  "As Suwayq",
  "Bawshar",
  "MUSCAT",
  "Mutrah",
  "Salalah",
  "Sohar",
  "Abbotabad",
  "Bahawalnagar",
  "Bahawalpur",
  "Burewala",
  "Chiniot",
  "Chishtian",
  "Dadu",
  "Daska",
  "Dera Ghazi Khan",
  "Faisalabad (Lyallpur)",
  "Gojra",
  "Gujranwala",
  "Gujrat",
  "Hafizabad",
  "ISLAMABAD",
  "Jacobabad",
  "Jaranwala",
  "Jhang",
  "Jhelum",
  "Kamoke",
  "Karachi",
  "Kasur",
  "Khairpur",
  "Khanewal",
  "Khanpur",
  "Kohat",
  "Lahore",
  "Larkana",
  "Mangora",
  "Mardan",
  "Mirpur Khas",
  "Multan",
  "Muridke",
  "Muzaffargharh",
  "Nawabshah",
  "Okara",
  "Pakpattan",
  "Peshawar",
  "Quetta",
  "Rahimyar Khan",
  "Rawalpindi",
  "Sadiqabad",
  "Sahiwal",
  "Sargodha",
  "Shakkarpur",
  "Sheikhu Pura",
  "Sialkote",
  "Sukkur",
  "Tandoadam",
  "Wah Cantonment",
  "KOROR",
  "PORT MORESBY",
  "ASUNCION",
  "Capiatá",
  "Ciudad del Este",
  "Fernando de la Mora",
  "Lambaré",
  "Luque",
  "San Lorenzo",
  "Arequipa",
  "Ayacucho",
  "Cajamarca",
  "Callao",
  "Chiclayo",
  "Chimbote",
  "Chincha Alta",
  "Cuzco",
  "Huancayo",
  "Huánuco",
  "Ica",
  "Huaraz",
  "Iquitos",
  "Juliaca",
  "LIMA",
  "Pisco",
  "Piura",
  "Pucallpa",
  "Puno",
  "Sullana",
  "Tacna",
  "Tarapoto",
  "Trujillo",
  "Angeles",
  "Angono",
  "Antipolo",
  "Apalit",
  "Arayat",
  "Bacolod",
  "Bacoor City",
  "Baguio",
  "Baliuag",
  "Batangas",
  "Bayambang",
  "Bayawan (Tulong)",
  "Baybay",
  "Biñan",
  "Binangonan",
  "Bocaue",
  "Butuan",
  "Cabanatuan",
  "Cabuyao",
  "Cadiz",
  "Cagayan de Oro",
  "Cainta",
  "Calamba",
  "Calapan",
  "Calbayog",
  "Calumpit",
  "Candaba",
  "Candelaria",
  "Capas",
  "Carcar",
  "Cauayan",
  "Cavite City",
  "Cebu",
  "Concepcion",
  "Consolacion",
  "Cotabato",
  "Dagupan",
  "Danao City",
  "Daraga (Locsin)",
  "Dasmariñas",
  "Davao",
  "Digos",
  "Dipolog",
  "Dumaguete",
  "Gapan",
  "Gen. Mariano Alvarez",
  "General Santos",
  "General Trias",
  "Gingoog",
  "Glan",
  "Guagua",
  "Guimba",
  "Hagonoy",
  "Himamaylan",
  "Ilagan",
  "Iligan",
  "Iloilo",
  "Imus City",
  "Iriga",
  "Jolo",
  "Kabankalan",
  "Kalookan (Caloocan)",
  "Kidapawan",
  "Koronadal",
  "La Trinidad",
  "Laoag",
  "Lapu-Lapu",
  "Las Piñas",
  "Legazpi",
  "Libmanan",
  "Philippines: Ligao",
  "Liloan",
  "Lipa",
  "Los Baños",
  "Lubao",
  "Lucena City",
  "Mabalacat",
  "Magalang",
  "Makati",
  "Malabalay",
  "Malabon",
  "Malasiqui",
  "Malita",
  "Malolos",
  "Mandaluyong",
  "Mandaue",
  "MANILA",
  "Marawi",
  "Marikina",
  "Marilao",
  "Mariveles",
  "Mati",
  "Mexico",
  "Meycauayan",
  "Midsayap",
  "Minglanilla",
  "Muntinlupa",
  "Naga (Camarines Sur)",
  "Naga (Cebu)",
  "Nasugbu",
  "Navotas",
  "Norzagaray",
  "Olongapo",
  "Ormoc",
  "Ozamis",
  "Pagadian",
  "Panabo",
  "Paranaque",
  "Pasay",
  "Pasig",
  "Pikit",
  "Plaridel",
  "Polomolok",
  "Porac",
  "Puerto Princesa",
  "Quezon City",
  "Rodriguez (Montalban)",
  "Roxas",
  "Sagay City",
  "San Carlos (Negros Occidental)",
  "San Carlos (Pangasinan)",
  "San Fernando (La Union)",
  "San Jose (Occidental Mindoro)",
  "San Fernando (Pampanga)",
  "San Jose City (Nueva Ecija)",
  "San Jose Del Monte",
  "San Mateo",
  "San Pablo",
  "San Pedro",
  "Santa Rosa",
  "Santiago",
  "Santo Tomas ( Davao Del Norte)",
  "Santo Tomas (Batangas)",
  "Sariaya",
  "Silang",
  "Silay",
  "Sorsogon",
  "Surigao",
  "Tabaco",
  "Tabuk",
  "Tacloban",
  "Taguig",
  "Tagum",
  "Talavera",
  "Talisay",
  "Tanauan",
  "Tanza",
  "Tarlac",
  "Taytay",
  "Trece Martires",
  "Tuguegarao",
  "Urdaneta",
  "Valencia",
  "Valenzuela",
  "Zamboanga",
  "Basilan",
  "ADAMSTOWN",
  "Bialystok",
  "Bielsko-Biala",
  "Bydgoszcz",
  "Bytom",
  "Chorzów",
  "Czestochowa",
  "Dabrowa Górnicza",
  "Elblag",
  "Gdansk",
  "Gdynia",
  "Gliwice",
  "Gorzów Wielkopolski",
  "Grudziadz",
  "Jastrzebie-Zdrój",
  "Kalisz",
  "Katowice",
  "Kielce",
  "Koszalin",
  "Kraków",
  "Legnica",
  "Lódz",
  "Lublin",
  "Olsztyn",
  "Opole",
  "Plock",
  "Poznan",
  "Radom",
  "Ruda Slaska",
  "Rybnik",
  "Rzeszów",
  "Slupsk",
  "Sosnowiec",
  "Szczecin",
  "Tarnów",
  "Torun",
  "Tychy",
  "Walbrzych",
  "WARSZAWA",
  "Wloclawek",
  "Wroclaw",
  "Zabrze",
  "Zielona Góra",
  "Amadora",
  "LISBOA",
  "Porto",
  "Braga",
  "Coimbra",
  "Funchal",
  "Vila Nova de Gaia",
  "Setubal",
  "Almada",
  "Arecibo",
  "Bayamón",
  "Caguas",
  "Carolina",
  "Guaynabo",
  "Ponce",
  "SAN JUAN",
  "Al-Rayyan",
  "Al-Khoor",
  "Al-Wakrah",
  "DOHA",
  "Busan (Pusan)",
  "Daegu (Taegu)",
  "Daejeon (Taejon)",
  "Gwangju (Kwangchu)",
  "Incheon",
  "SEOUL",
  "Ulsan",
  "Icheon",
  "Andong",
  "Asan",
  "Boryeong",
  "Bucheon (Puchon)",
  "Changwon",
  "Cheonan",
  "Cheongju",
  "Chuncheon",
  "Chungju",
  "Gangneung (Kangnung)",
  "Geoje",
  "Gimcheon",
  "Gimhae (Kimhae)",
  "Gimje",
  "Gongju",
  "Goyang",
  "Gumi (Kumi)",
  "Gunpo (Kunpo)",
  "Gunsan (Kunsan)",
  "Gwangmyeong (Kwangmyong)",
  "Gwangyang",
  "Gyeongju (Kyongju)",
  "Gyeongsan",
  "Iksan (Iri)",
  "Jecheon (Chechon)",
  "Jeju (Cheju)",
  "Jeongeup",
  "Jeonju (Chonchu)",
  "Jinhae (Chinhae)",
  "Jinju (Chinju)",
  "Masan",
  "Miryang",
  "Mokpo",
  "Nonsan",
  "Pohang",
  "Sacheon",
  "Sangju",
  "Seongnam",
  "Seosan",
  "Suncheon",
  "Suwon (Puwan)",
  "Tongyeong",
  "Uijeongbu (Eujeongbu)",
  "Wonju",
  "Yangsan",
  "Yeongcheon",
  "Yeongju",
  "Yeosu",
  "Balti (Beltsy)",
  "CHISINAU (KISHINEV)",
  "Juba",
  "Malakal",
  "Wau",
  "SAINT-DENIS",
  "Saint-Paul",
  "Arad",
  "Bacau",
  "Baia Mare",
  "Botosani",
  "Braila",
  "Brasov",
  "BUCURESTI",
  "Buzau",
  "Cluj-Napoca",
  "Constanta",
  "Craiova",
  "Drobeta Turnu-Severin",
  "Focsani",
  "Galati",
  "Iasi",
  "Oradea",
  "Piatra Neamt",
  "Pitesti",
  "Ploiesti",
  "Rimnicu Vilcea",
  "Satu-Mare",
  "Sibiu",
  "Suceava",
  "Timisoara",
  "Tirgu-Mures",
  "Abakan",
  "Achinsk",
  "Almetievsk",
  "Anapa",
  "Angarsk",
  "Arkhangelsk",
  "Armavir",
  "Artem (Primorskiy Krai)",
  "Arzamas",
  "Astrakhan",
  "Balakovo",
  "Balashikha",
  "Barnaul",
  "Bataisk",
  "Belgorod",
  "Belovo",
  "Berezniki",
  "Biisk",
  "Blagoveshchensk (Amurskaya oblast)",
  "Bor",
  "Bratsk",
  "Bryansk",
  "Chaykovsky",
  "Cheboksary",
  "Chelyabinsk",
  "Cherepovets",
  "Cherkessk",
  "Chita",
  "Derbent",
  "Dimitrovgrad",
  "Domodedovo",
  "Dzerzhinsk (Nizhegorodskaya oblast)",
  "Ekaterinburg",
  "Elektrostal",
  "Elets",
  "Elista",
  "Engels",
  "Esentuky",
  "Groznyi",
  "Hasaviurt",
  "Irkutsk",
  "Ivanovo",
  "Izhevsk",
  "Kaliningrad (Kaliningradskaya oblast)",
  "Kaluga",
  "Kamensk-Uralsky",
  "Kamyshin",
  "Kaspiysk",
  "Kazan",
  "Kemerovo",
  "Khabarovsk",
  "Khimki",
  "Kirov",
  "Kiselevsk",
  "Kislovodsk",
  "Kolomna",
  "Komsomolsk-na-Amure",
  "Kopeysk",
  "Korolev (Moskovskaya oblast)",
  "Kostroma",
  "Kovrov",
  "Krasnodar",
  "Krasnogorsk",
  "Krasnoyarsk",
  "Kurgan",
  "Kursk",
  "Kyzyl",
  "Leninsk-Kuznetsky",
  "Lipetsk",
  "Lyubertsy",
  "Magadan",
  "Magnitogorsk",
  "Maikop",
  "Makhachkala",
  "Mezhdurechensk",
  "Miass",
  "MOSKVA",
  "Murmansk",
  "Murom",
  "Mytishchi",
  "Naberezhnye Tchelny",
  "Nakhodka",
  "Naltchik",
  "Nazran",
  "Neftekamsk",
  "Nefteyugansk",
  "Nevinnomyssk",
  "Nizhnekamsk",
  "Nizhnevartovsk",
  "Nizhny Novgorod",
  "Nizhny Tagil",
  "Noginsk",
  "Norilsk",
  "Novocheboksarsk",
  "Novocherkassk",
  "Novokuybishevsk",
  "Novokuznetsk",
  "Novomoskovsk (Tulskaya oblast)",
  "Novorossiysk",
  "Novoshakhtinsk",
  "Novosibirsk",
  "Novotroitsk",
  "Novy Urengoy",
  "Noyabrsk",
  "Obninsk",
  "Odintsovo",
  "Oktyabrsky",
  "Omsk",
  "Orekhovo-Zuevo",
  "Orel",
  "Orenburg",
  "Orsk",
  "Penza",
  "Perm",
  "Pervouralsk",
  "Petropavlovsk-Kamchatsky",
  "Petrozavodsk",
  "Podolsk",
  "Prokopyevsk",
  "Pskov",
  "Pushkino",
  "Pyatigorsk",
  "Rostov-na-Donu",
  "Rubtsovsk",
  "Ryazan",
  "Rybinsk",
  "Salavat",
  "Samara (Samarskaya oblast)",
  "Saransk",
  "Sarapyul",
  "Saratov",
  "Sergiev Posad",
  "Serov",
  "Serpukhov",
  "Severodvinsk",
  "Seversk",
  "Shakhty",
  "Shchelkovo",
  "Smolensk",
  "Sochi",
  "St. Petersburg",
  "Stary Oskol",
  "Stavropol",
  "Sterlitamak",
  "Surgut",
  "Syktivkar",
  "Syzran",
  "Taganrog",
  "Tambov",
  "Tobolsk",
  "Tolyatti",
  "Tomsk",
  "Tula",
  "Tver",
  "Tyumen",
  "Ufa",
  "Uhta",
  "Ulan-Ude",
  "Ulyanovsk",
  "Ussuriisk",
  "Velikie Luky",
  "Velikiy Novgorod",
  "Vladikavkaz (Osetinskaya ASSR)",
  "Vladimir",
  "Vladivostok",
  "Volgodonsk",
  "Volgograd",
  "Vologda",
  "Volzhsky",
  "Voronezh",
  "Yakutsk",
  "Yaroslavl",
  "Yoshkar-Ola",
  "Yuzhno-Sakhalinsk",
  "Zheleznodorozhny",
  "Zhukovsky",
  "Zlatoust",
  "Gubkin",
  "Asbest",
  "Glazov",
  "Kansk",
  "Solikamsk",
  "Ust-Ulimsk",
  "Vorkuta",
  "Zelenodolsk",
  "Zheleznogorsk",
  "Butare",
  "Gitarama",
  "KIGALI",
  "JAMESTOWN",
  "BASSETERRE",
  "CASTRIES",
  "SAINT-PIERRE",
  "KINGSTOWN",
  "APIA",
  "SAN MARINO",
  "SAO TOME",
  "Abha",
  "Ad-Dammam",
  "Al-Hawiyah",
  "Al-Hufuf",
  "Al-Jubayl",
  "Al-Kharj",
  "Al-Khubar",
  "Al-Madinah",
  "Al-Mubarraz",
  "Al-Qurrayyat",
  "Ar'ar",
  "Ath-Thuqbah",
  "At-Ta'if",
  "Buraydah",
  "Hafar al-Batin",
  "Ha'il",
  "Jiddah",
  "Jizan",
  "Khamis Mushayt",
  "Makkah",
  "Najran (Aba as-Suud)",
  "RIYADH",
  "Sekaka",
  "Unayzah",
  "Yanbu al-Bahr",
  "DAKAR",
  "Diourbel",
  "Guediawaye",
  "Kaolack",
  "Mbour",
  "Pikine",
  "Rufisque",
  "Saint Louis",
  "Thiès",
  "Ziguinchor",
  "BEOGRAD (BELGRADE)",
  "Cacak",
  "Kragujevac",
  "Kraljevo",
  "Kruševac",
  "Leskovac",
  "Niš",
  "Novi Sad",
  "Pancevo",
  "Šabac",
  "Smederevo",
  "Subotica",
  "Zrenjanin",
  "VICTORIA",
  "FREETOWN",
  "SINGAPORE",
  "BRATISLAVA",
  "Kosice",
  "LJUBLJANA",
  "Maribor",
  "HONIARA",
  "Alexandra",
  "Benoni",
  "BLOEMFONTEIN",
  "Boksburg",
  "Botshabelo",
  "CAPE TOWN",
  "Durban",
  "Germiston",
  "Johannesburg",
  "Kathlehong",
  "Kempton Park",
  "Khayelitsa",
  "Kimberley",
  "Mangaung",
  "Pietermaritzburg",
  "Port Elizabeth",
  "PRETORIA",
  "Roodepoort",
  "Soweto",
  "Springs",
  "Tembisa",
  "Umlazi",
  "Vereeniging",
  "Albacete",
  "Alcalá de Henares",
  "Alcobendas",
  "Alcorcón",
  "Algeciras",
  "Alicante",
  "Almería",
  "Badajoz",
  "Badalona",
  "Baracaldo",
  "Barcelona",
  "Bilbao",
  "Burgos",
  "Cádiz",
  "Castellón de la Plana",
  "A Coruña",
  "Donostia - San Sebastián",
  "Dos Hermanas",
  "Elche",
  "Fuenlabrada",
  "Getafe",
  "Gijón",
  "Granada",
  "Hospitalet de Llobregat",
  "Huelva",
  "Jaén",
  "Jérez de la Frontera",
  "Leganés",
  "Lleida",
  "Logroño",
  "MADRID",
  "Málaga",
  "Marbella",
  "Mataró",
  "Móstoles",
  "Murcia",
  "Ourense",
  "Oviedo",
  "Palma de Mallorca",
  "Palmas de Gran Canaria",
  "Pamplona",
  "Parla",
  "Reus",
  "Sabadell",
  "San Cristóbal de La Laguna",
  "Santa Coloma de Gramanet",
  "Santa Cruz de Tenerife",
  "Santander",
  "Sevilla",
  "Tarragona",
  "Telde",
  "Terrassa",
  "Torrejón de Ardoz",
  "Torrevieja",
  "Valladolid",
  "Vigo",
  "Vitoria-Gasteiz",
  "Zaragoza",
  "Palma",
  "Las Palmas de Gran Canaria",
  "La Coruña",
  "COLOMBO",
  "Dehiwala-Mount Lavinia",
  "Kandy",
  "Moratuwa",
  "Negombo",
  "Sri Jayawardanapura Kotte",
  "Gaza",
  "Hebron",
  "Jabalya",
  "Khan Yunis",
  "Nablus",
  "Rafah",
  "PARAMARIBO",
  "MBABANE",
  "Göteborg",
  "Helsingborg",
  "Jönköping",
  "Linköping",
  "Malmö",
  "Norrköping",
  "Orebro",
  "STOCKHOLM",
  "Umeå",
  "Uppsala",
  "Västerås",
  "Baden-Brugg",
  "Bâle",
  "BERNE",
  "Fribourg",
  "Genève",
  "Lausanne",
  "Lugano",
  "Luzern",
  "Olten-Zofingen",
  "St. Gallen",
  "Winterthur",
  "Zug",
  "Zürich",
  "DUSHANBE",
  "Khujand",
  "SKOPJE",
  "Kumanovo",
  "Amnat Charoen",
  "Ang Thong",
  "BANGKOK",
  "Buri Ram",
  "Chachoengsao",
  "Chai Nat",
  "Chaiyaphum",
  "Chanthaburi",
  "Chiang Mai",
  "Chiang Rai",
  "Chon Buri",
  "Chumphon",
  "Kalasin",
  "Kamphaeng Phet",
  "Kanchanaburi",
  "Khon Kaen",
  "Krabi",
  "Lampang",
  "Loei",
  "Lop Buri",
  "Lamphun",
  "Mae Hong Son",
  "Maha Sarakham",
  "Mukdahan",
  "Nakhon Nayok",
  "Nakhon Phanom",
  "Nakhon Pathom",
  "Nakhon Ratchasima",
  "Nakhon Sawan",
  "Nakhon Si Thammarat",
  "Nan",
  "Narathiwat",
  "Nong Bua Lam Phu",
  "Nong Khai",
  "Nonthaburi",
  "Pathum Thani",
  "Pattani",
  "Phatthalung",
  "Phangnga",
  "Phayao",
  "Phetchabun",
  "Phetchaburi",
  "Phichit",
  "Phitsanulok",
  "Phra Nakhon Si Ayutthaya",
  "Phrae",
  "Phuket",
  "Prachin Buri",
  "Prachuap Khiri Khan",
  "Ratchaburi",
  "Ranong",
  "Rayong",
  "Roi Et",
  "Sa Kaeo",
  "Sakon Nakhon",
  "Samut Prakan",
  "Samut Sakhon",
  "Samut Songkhram",
  "Saraburi",
  "Satun",
  "Sing Buri",
  "Si Sa Ket",
  "Songkhla",
  "Sukhothai",
  "Suphan Buri",
  "Surat Thani",
  "Surin",
  "Tak",
  "Trat",
  "Trang",
  "Ubon Ratchathani",
  "Udon Thani",
  "Uttaradit",
  "Yasothon",
  "Uthai Thani",
  "Yala",
  "Sakon Sakhon",
  "DILI",
  "NUKU'ALOFA",
  "PORT-OF-SPAIN",
  "Adana",
  "Adiyaman",
  "Afyonkarahisar",
  "Agri",
  "Akhisar",
  "Aksaray",
  "Alanya (Antalya)",
  "ANKARA",
  "Antalya",
  "Aydin",
  "Balikesir",
  "Bandirma",
  "Batman",
  "Bolu",
  "Bursa",
  "Ceyhan",
  "Cizre",
  "Çanakkale",
  "Çorlu",
  "Çorum",
  "Denizli",
  "Diyarbakir",
  "Düzce",
  "Edirne",
  "Elazig",
  "Eregli",
  "Erzurum",
  "Eskisehir",
  "Gaziantep",
  "Giresun",
  "Hatay",
  "Inegöl",
  "Iskenderun",
  "Isparta",
  "Istanbul",
  "Izmir",
  "Kahramanmaras",
  "Karabük",
  "Karaman",
  "Kayseri",
  "Kirikkale",
  "Kirsehir",
  "Kiziltepe",
  "Kocaeli",
  "Konya",
  "Kütahya",
  "Lüleburgaz",
  "Malatya",
  "Manisa",
  "Mersin",
  "Nazilli",
  "Nigde",
  "Ordu",
  "Osmaniye",
  "Polatli",
  "Rize",
  "Sakarya",
  "Samsun",
  "Sanliurfa",
  "Siirt",
  "Sivas",
  "Siverek",
  "Tarsus",
  "Tekirdag",
  "Tokat",
  "Trabzon",
  "Turgutlu ( Manisa)",
  "Usak",
  "Van",
  "Yalova",
  "Zonguldak",
  "ASHKHABAD",
  "Türkmenabat (Chardzhou)",
  "Tashauz",
  "GRAND TURK",
  "FUNAFUTI",
  "Gulu",
  "KAMPALA",
  "Alchevsk",
  "Belaya Tserkov (Bila Crkva)",
  "Berdyansk",
  "Cherkassy",
  "Chernigov",
  "Chernovtsy",
  "Dneprodzerzhinsk",
  "Dnepropetrovsk",
  "Donetsk (Donestskaya oblast)",
  "Enakievo (Yenakievo)",
  "Evpatoriya (Yevpatoriya)",
  "Gorlovka",
  "Ivano-Frankovsk",
  "Kamyanetsk Podilsky",
  "Kertch",
  "Kharkov",
  "Kherson",
  "Khmelnitsky (Hmilnyk)",
  "KIEV",
  "Kirovograd",
  "Kramatorsk",
  "Krasny Lutch",
  "Krementchug",
  "Kryvy Rig",
  "Lugansk",
  "Lutsk",
  "Lvov",
  "Lysychansk",
  "Makeyevka",
  "Mariupol",
  "Melitopol",
  "Mykolaiv (Nikolaevskaya oblast)",
  "Nikopol",
  "Odessa",
  "Pavlograd",
  "Poltava",
  "Rivne",
  "Sevastopol",
  "Severodonetsk",
  "Simferopol",
  "Slavyansk",
  "Stakhanov",
  "Sumy",
  "Ternopol",
  "Uzhgorod",
  "Vinnutsya",
  "Yevpatoriya",
  "Zaporozhye",
  "Zhitomir",
  "Aberdeen",
  "Aberdeenshire",
  "Aldershot",
  "Angus",
  "Basildon/North Benfleet",
  "Bedford/Kempston",
  "Belfast",
  "Birkenhead",
  "Blackburn/Darwen",
  "Blackpool",
  "Bournemouth",
  "Brighton/Worthing/Littlehampton",
  "Bristol",
  "Burnley/Nelson",
  "Cardiff",
  "Cheltenham/Charlton Kings",
  "Chesterfield/Staveley",
  "Colchester",
  "Coventry/Bedworth",
  "Crawley",
  "Dearne Valley",
  "Derby",
  "Doncaster",
  "Dumfries & Galloway",
  "Dundee",
  "East Ayrshire",
  "East Dunbartonshire",
  "Eastbourne",
  "Edinburgh",
  "Exeter",
  "Falkirk",
  "Fife",
  "Glasgow",
  "Gloucester",
  "Grimsby/Cleethorpes",
  "Hastings/Bexhill",
  "High Wycombe",
  "Highland",
  "Ipswich",
  "Kingston-upon-Hull",
  "Leicester",
  "Lincoln",
  "Liverpool",
  "LONDON",
  "Luton/Dunstable",
  "Manchester",
  "Mansfield",
  "Milton Keynes",
  "Newport",
  "North Ayrshire",
  "North Lanarkshire",
  "Northampton",
  "Norwich",
  "Nottingham",
  "Nuneaton",
  "Oxford",
  "Perth & Kinross",
  "Plymouth",
  "Portsmouth",
  "Preston",
  "Reading/Wokingham",
  "Renfrewshire",
  "Scottish Borders",
  "Sheffield",
  "Slough",
  "South Ayrshire",
  "South Lanarkshire",
  "Southampton",
  "Southend",
  "Southport/Formby",
  "St. Albans/Hatfield",
  "Sunderland",
  "Swansea",
  "Swindon",
  "Teesside",
  "Telford",
  "Thanet",
  "The Medway Towns",
  "The Potteries",
  "Torbay",
  "Tyneside",
  "Warrington",
  "West Lothian",
  "West Midlands",
  "West Yorkshire",
  "Wigan",
  "York",
  "Arusha",
  "Dar es Salaam",
  "DODOMA",
  "Mbeya",
  "Morogoro",
  "Mwanza",
  "Shinyanga",
  "Tanga",
  "Zanzibar",
  "Abilene (TX)",
  "Akron (OH)",
  "Albuquerque (NM)",
  "Alexandria (VA)",
  "Allentown (PA)",
  "Amarillo (TX)",
  "Anaheim (CA)",
  "Anchorage (AK)",
  "Ann Arbor (MI)",
  "Antioch (CA)",
  "Arlington (TX)",
  "Arvada (CO)",
  "Athens (GA)",
  "Atlanta (GA)",
  "Augusta (GA)",
  "Aurora (CO)",
  "Aurora (IL)",
  "Austin (TX)",
  "Bakersfield (CA)",
  "Baltimore (MD)",
  "Baton Rouge (LA)",
  "Beaumont (TX)",
  "Bellevue (WA)",
  "Berkeley (CA)",
  "Billings (MT)",
  "Birmingham (AL)",
  "Boise City (ID)",
  "Boston (MA)",
  "Boulder (CO)",
  "Bridgeport (CT)",
  "Brownsville (TX)",
  "Buffalo (NY)",
  "Burbank (CA)",
  "Carlsbad (CA)",
  "Cambridge (MA)",
  "Cape Coral (FL)",
  "Carrollton (TX)",
  "Cary (NC)",
  "Cedar Rapids (IA)",
  "Centennial (CO)",
  "Chandler (AZ)",
  "Charleston (SC)",
  "Charlotte (NC)",
  "Chattanooga (TN)",
  "Chesapeake (VA)",
  "Chicago (IL)",
  "Chula Vista (CA)",
  "Cincinnati (OH)",
  "Clarksville (TN)",
  "Clearwater (FL)",
  "Cleveland (OH)",
  "Colorado Springs (CO)",
  "Columbia (MO)",
  "Columbia (SC)",
  "Columbus (GA)",
  "Columbus (OH)",
  "Concord (CA)",
  "Coral Springs (FL)",
  "Corona (CA)",
  "Corpus Christi (TX)",
  "Costa Mesa (CA)",
  "Dallas (TX)",
  "Daly City (CA)",
  "Davenport (IA)",
  "Dayton (OH)",
  "Denton (TX)",
  "Denver (CO)",
  "Des Moines (IA)",
  "Detroit (MI)",
  "Downey (CA)",
  "Durham (NC)",
  "El Monte (CA)",
  "El Paso (TX)",
  "Elgin (IL)",
  "Elizabeth (NJ)",
  "Elk Grove (CA)",
  "Erie (PA)",
  "Escondido (CA)",
  "Eugene (OR)",
  "Evansville (IN)",
  "Everett (WA)",
  "Fairfield (CA)",
  "Fargo (ND)",
  "Fayetteville (NC)",
  "Flint (MI)",
  "Fontana (CA)",
  "Fort Collins (CO)",
  "Fort Lauderdale (FL)",
  "Fort Wayne (IN)",
  "Fort Worth (TX)",
  "Fremont (CA)",
  "Fresno (CA)",
  "Frisco (TX)",
  "Fullerton (CA)",
  "Gainesville (FL)",
  "Garden Grove (CA)",
  "Garland (TX)",
  "Gilbert (AZ)",
  "Glendale (AZ)",
  "Glendale (CA)",
  "Grand Prairie (TX)",
  "Grand Rapids (MI)",
  "Green Bay (WI)",
  "Greensboro (NC)",
  "Gresham (OR)",
  "Hampton (VA)",
  "Hartford (CT)",
  "Hayward (CA)",
  "Henderson (NV)",
  "Hialeah (FL)",
  "High Point City (NC)",
  "Hollywood (FL)",
  "Urban Honolulu (HI)",
  "Houston (TX)",
  "Huntington Beach (CA)",
  "Huntsville (AL)",
  "Independence (MO)",
  "Indianapolis (IN)",
  "Inglewood (CA)",
  "Irvine (CA)",
  "Irving (TX)",
  "Jackson (MS)",
  "Jacksonville (FL)",
  "Jersey City (NJ)",
  "Joliet (IL)",
  "Kansas City (KS)",
  "Kansas City (MO)",
  "Killeen (TX)",
  "Knoxville (TN)",
  "Lafayette (LA)",
  "Lakewood (CO)",
  "Lancaster (CA)",
  "Lansing (MI)",
  "Laredo (TX)",
  "Las Vegas (NV)",
  "Lexington-Fayette (KY)",
  "Lincoln (NE)",
  "Little Rock (AR)",
  "Long Beach (CA)",
  "Los Angeles (CA)",
  "Louisville (KY)",
  "Lowell (MA)",
  "Lubbock (TX)",
  "Madison (WI)",
  "Manchester (NH)",
  "McAllen (TX)",
  "McKinney City (TX)",
  "Memphis (TN)",
  "Mesa (AZ)",
  "Mesquite (TX)",
  "Miami (FL)",
  "Miami Gardens (FL)",
  "Midland City (TX)",
  "Milwaukee (WI)",
  "Minneapolis (MN)",
  "Miramar (FL)",
  "Mobile (AL)",
  "Modesto (CA)",
  "Montgomery (AL)",
  "Moreno Valley (CA)",
  "Murrieta (CA)",
  "Murfreesboro (TN)",
  "Naperville (IL)",
  "Nashville-Davidson (TN)",
  "New Haven (CT)",
  "New Orleans (LA)",
  "New York (NY)",
  "Newark (NJ)",
  "Newport News (VA)",
  "Norfolk (VA)",
  "Norman (OK)",
  "North Charleston (SC)",
  "North Las Vegas (NV)",
  "Norwalk (CA)",
  "Oakland (CA)",
  "Oceanside (CA)",
  "Odessa (TX)",
  "Oklahoma City (OK)",
  "Olathe (KS)",
  "Omaha (NE)",
  "Ontario (CA)",
  "Orange (CA)",
  "Orlando (FL)",
  "Overland Park (KS)",
  "Oxnard (CA)",
  "Palmdale (CA)",
  "Palm Bay City (FL)",
  "Pasadena (CA)",
  "Pasadena (TX)",
  "Paterson (NJ)",
  "Pembroke Pines (FL)",
  "Peoria (AZ)",
  "Peoria (IL)",
  "Philadelphia (PA)",
  "Phoenix (AZ)",
  "Pittsburgh (PA)",
  "Plano (TX)",
  "Pomona (CA)",
  "Pompano Beach (FL)",
  "Port St. Lucie (FL)",
  "Portland (OR)",
  "Providence (RI)",
  "Provo (UT)",
  "Pueblo (CO)",
  "Raleigh (NC)",
  "Rancho Cucamonga (CA)",
  "Reno (NV)",
  "Rialto (CA)",
  "Richardson (TX)",
  "Richmond (CA)",
  "Richmond (VA)",
  "Riverside (CA)",
  "Rochester (MN)",
  "Rochester (NY)",
  "Rockford (IL)",
  "Roseville (CA)",
  "Round Rock (TX)",
  "Sacramento (CA)",
  "Salem (OR)",
  "Salinas (CA)",
  "Salt Lake City (UT)",
  "San Antonio (TX)",
  "San Bernardino (CA)",
  "San Buenaventura (CA)",
  "San Diego (CA)",
  "San Francisco (CA)",
  "San Jose (CA)",
  "Santa Ana (CA)",
  "Santa Clara (CA)",
  "Santa Clarita (CA)",
  "Santa Maria (CA)",
  "Santa Rosa (CA)",
  "Savannah (GA)",
  "Scottsdale (AZ)",
  "Seattle (WA)",
  "Shreveport (LA)",
  "Simi Valley (CA)",
  "Sioux Falls (SD)",
  "South Bend (IN)",
  "Spokane (WA)",
  "Springfield (IL)",
  "Springfield (MA)",
  "Springfield (MO)",
  "St. Louis (MO)",
  "St. Paul (MN)",
  "St. Petersburg (FL)",
  "Stamford (CT)",
  "Sterling Heights (MI)",
  "Stockton (CA)",
  "Sunnyvale (CA)",
  "Surprise (AZ)",
  "Syracuse (NY)",
  "Tacoma (WA)",
  "Tallahassee (FL)",
  "Tampa (FL)",
  "Temecula (CA)",
  "Tempe (AZ)",
  "Thornton (CO)",
  "Thousand Oaks (CA)",
  "Toledo (OH)",
  "Topeka (KS)",
  "Torrance (CA)",
  "Tucson (AZ)",
  "Tulsa (OK)",
  "Vallejo (CA)",
  "Vancouver (WA)",
  "Victorville City (CA)",
  "Virginia Beach (VA)",
  "Visalia (CA)",
  "Waco (TX)",
  "Warren (MI)",
  "WASHINGTON (DC)",
  "Waterbury (CT)",
  "West Covina (CA)",
  "West Jordan (UT)",
  "West Palm Beach (FL)",
  "West Valley City (UT)",
  "Westminster (CO)",
  "Wichita (KS)",
  "Wichita Falls (TX)",
  "Wilmington (NC)",
  "Winston-Salem (NC)",
  "Worcester (MA)",
  "Yonkers (NY)",
  "Arlington (VA)",
  "Brandon (FL)",
  "East Los Angeles (CA)",
  "Enterprise (NV)",
  "Metairie (LA)",
  "Paradise (NV)",
  "Spring Valley (NV)",
  "Sunrise Manor (NV)",
  "Lewisville (TX)",
  "Portsmouth (VA)",
  "Gary (IN)",
  "Livonia (MI)",
  "CHARLOTTE AMALIE",
  "MONTEVIDEO",
  "Almalyk",
  "Andizhan",
  "Angren",
  "Banjzak",
  "Bukhara",
  "Chirchik",
  "Fergana",
  "Karshi",
  "Kokand",
  "Margilan",
  "Namangan",
  "Navoi",
  "Nukus",
  "Samarkand",
  "TASHKENT",
  "Termez",
  "Urgentch",
  "PORT VILA",
  "Acarigua-Araure",
  "Anaco(F) (Capital)",
  "Barcelona-Puerto La Cruz",
  "Barinas",
  "Barquisimeto",
  "Baruta",
  "Cabimas",
  "Cagua",
  "CARACAS",
  "Carora",
  "Carúpano",
  "Catia la Mar",
  "Ciudad Bolívar",
  "Ciudad Guayana",
  "Ciudad Ojeda",
  "Coro",
  "Cua",
  "Cumaná",
  "El Silencio",
  "El Tigre",
  "Guanare",
  "Guarenas",
  "Guacara",
  "Guatire",
  "Los Guayos",
  "Los Teques",
  "Maracaibo",
  "Maracay",
  "Maturín",
  "Naguanagua",
  "Ocumare Del Tuy",
  "Petare",
  "Pozuelos (F) (Capital)",
  "Puerto Cabello",
  "Puerto La Cruz",
  "Punto Fijo",
  "San Fernando de Apure",
  "San Francisco",
  "Santa Lucia",
  "Táriba",
  "Tocuyito",
  "Turmero",
  "Valera",
  "META-UTU",
  "Adan",
  "SANA'A",
  "Al-Hudaydah (Hodeidah)",
  "Al-Mukalla",
  "Ibb",
  "Ta'izz",
  "Chingola",
  "Chipata",
  "Kabwe",
  "Kasama",
  "Kitwe",
  "Livingstone",
  "Luanshya",
  "LUSAKA",
  "Mufulira",
  "Ndola",
  "Bulawayo",
  "Chitungwiza",
  "Gweru",
  "HARARE",
  "Mutare",
  "null",
  "based"
];
