// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChmRkc-1ohhTXZ6yCAR3eFNUJGywYtz7Q',
    appId: '1:1080400165198:web:6a94f0b1709d5a5ffd461f',
    messagingSenderId: '1080400165198',
    projectId: 'videocall-65fc5',
    authDomain: 'videocall-65fc5.firebaseapp.com',
    databaseURL: 'https://videocall-65fc5.firebaseio.com',
    storageBucket: 'videocall-65fc5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD4q5Q9gB2OhIu1WhYFVpNPCX5xKCJAY8',
    appId: '1:1080400165198:android:2fd5260e7062a29cfd461f',
    messagingSenderId: '1080400165198',
    projectId: 'videocall-65fc5',
    databaseURL: 'https://videocall-65fc5.firebaseio.com',
    storageBucket: 'videocall-65fc5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL0wPr7vCDbBill-ZddQtx-iVBBbAClD0',
    appId: '1:1080400165198:ios:d4feeb0e51f100a3fd461f',
    messagingSenderId: '1080400165198',
    projectId: 'videocall-65fc5',
    databaseURL: 'https://videocall-65fc5.firebaseio.com',
    storageBucket: 'videocall-65fc5.appspot.com',
    androidClientId: '1080400165198-fub7451h5oq9r5mabvvn5hn5l5vvbikv.apps.googleusercontent.com',
    iosClientId: '1080400165198-6sp5tt3kn7castj0dh1fqhaegu1tttch.apps.googleusercontent.com',
    iosBundleId: 'com.example.wealtherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL0wPr7vCDbBill-ZddQtx-iVBBbAClD0',
    appId: '1:1080400165198:ios:d4feeb0e51f100a3fd461f',
    messagingSenderId: '1080400165198',
    projectId: 'videocall-65fc5',
    databaseURL: 'https://videocall-65fc5.firebaseio.com',
    storageBucket: 'videocall-65fc5.appspot.com',
    androidClientId: '1080400165198-fub7451h5oq9r5mabvvn5hn5l5vvbikv.apps.googleusercontent.com',
    iosClientId: '1080400165198-6sp5tt3kn7castj0dh1fqhaegu1tttch.apps.googleusercontent.com',
    iosBundleId: 'com.example.wealtherApp',
  );
}
